// Plain-language descriptions of AST flags, used in refactor feedback.
import type { AstFlag } from '../../content/ids.ts';

export const FLAG_TEXT: Record<AstFlag, string> = {
  import_used: 'an import',
  print_call: 'a print call',
  input_call: 'an input() call',
  global_stmt: 'a global statement',
  while_no_update: 'a while loop whose condition never changes',
  while_true_no_break: 'a while True loop with no break',
  acc_reset_in_loop: 'a running total that is reset inside the loop',
  range_len_index: 'a range(len(...)) loop that indexes the list',
  mutate_while_iterating: 'a list that is changed while looping over it',
  shadow_builtin: 'a variable named after a built-in such as list or sum',
  mutable_default: 'a list or dict as a default argument',
  missing_return: 'a path that ends without return',
  return_print: 'return print(...)',
  bare_function_name: 'a function name used without calling it',
  compare_to_true: 'a comparison with True or False',
  if_return_bool_literal: 'an if/else that returns True or False',
  is_literal: "'is' used to compare with a value",
  or_with_literal: "an 'or' followed by a bare value",
  none_from_inplace: 'the None result of an in-place method such as sort()',
  discarded_str_method: 'a string method whose result is thrown away',
  open_without_with: "open() without 'with'",
  round_in_loop: 'round() in the middle of the calculation',
  csv_ext_literal: "a '.csv' extension written into the code",
  bare_except: 'a bare except:',
  loop_present: 'a loop',
  for_each: 'a for-each loop (for item in items)',
  enumerate_used: 'enumerate()',
  dict_get_used: 'dict.get() with a default',
  fstring_used: 'an f-string',
  early_return: 'an early return',
  with_open: "'with open(...)'",
  header_index_lookup: 'a column lookup by header name',
  recursion_present: 'a recursive call',
  docstring_present: 'a docstring',
};
