// Reference: loops.
import type { Recipe } from '../recipeSchema.ts';

const recipes: Recipe[] = [
  {
    id: 'count-from-a-to-b',
    task: 'Count from one number up to another',
    group: 'loops',
    also: ['range', 'for loop', 'counting'],
    topicId: 'for-loops-range',
    code: "for n in range(2, 6):\n    print(n)\n",
    note: '`range(2, 6)` gives `2, 3, 4, 5`: the start is included and the stop is not, which is the usual place students are off by one.',
  },
  {
    id: 'loop-with-the-index',
    task: 'Loop over a list and also get the position of each item',
    group: 'loops',
    also: ['enumerate', 'index', 'position'],
    topicId: 'for-loops-range',
    code: "names = ['Ada', 'Bo', 'Cy']\nfor i, name in enumerate(names):\n    print(i, name)\n",
    note: '`enumerate(names)` is the idiom; `for i in range(len(names))` and then indexing `names[i]` does the same job but is easier to get wrong.',
  },
  {
    id: 'loop-two-lists-together',
    task: 'Loop over two lists at the same time',
    group: 'loops',
    also: ['zip', 'pair up', 'parallel lists'],
    topicId: 'for-loops-range',
    code: "names = ['Ada', 'Bo']\nmarks = [72, 91]\nfor name, mark in zip(names, marks):\n    print(name, mark)\n",
    note: '`zip()` stops at the shorter list without raising, so if the two lists are supposed to be the same length, check `len(names) == len(marks)` yourself first.',
  },
  {
    id: 'repeat-a-fixed-number-of-times',
    task: 'Repeat something a fixed number of times',
    group: 'loops',
    also: ['repeat', 'n times'],
    topicId: 'for-loops-range',
    code: "for _ in range(3):\n    print('hi')\n",
    note: '`_` is a normal variable name, used by convention to say "the loop variable itself does not matter here", only the number of repeats does.',
  },
  {
    id: 'running-total-in-a-loop',
    task: 'Keep a running total while looping',
    group: 'loops',
    also: ['accumulator', 'sum in a loop', 'total'],
    topicId: 'for-loops-range',
    code: "marks = [72, 45, 91]\ntotal = 0\nfor m in marks:\n    total += m\nprint(total)\n",
    note: 'The accumulator (`total = 0`) has to be created before the loop starts; setting it inside the loop resets it back to 0 on every pass.',
  },
  {
    id: 'break-and-continue',
    task: 'Stop a loop early or skip one item in it',
    group: 'loops',
    also: ['break', 'continue', 'skip', 'exit loop'],
    topicId: 'while-nested-loops',
    code: "for n in range(10):\n    if n == 5:\n        break\n    if n % 2 == 0:\n        continue\n    print(n)\n",
    note: '`break` leaves the loop right away; `continue` skips only the rest of that one pass and moves on to the next item. Neither works outside a loop.',
  },
  {
    id: 'while-loop-until-condition',
    task: 'Loop until something happens rather than a fixed number of times',
    group: 'loops',
    also: ['while', 'until', 'condition loop'],
    topicId: 'while-nested-loops',
    code: "n = 20\nsteps = 0\nwhile n != 1:\n    n = n // 2 if n % 2 == 0 else n * 3 + 1\n    steps += 1\nprint(steps)\n",
    note: 'A `while` loop needs something inside it that moves the condition towards being false; leave that out and the loop never ends.',
  },
  {
    id: 'loop-over-a-string',
    task: 'Loop over the characters of a string',
    group: 'loops',
    also: ['characters', 'iterate string'],
    topicId: 'strings',
    code: "word = 'cat'\nfor ch in word:\n    print(ch.upper())\n",
    note: 'A string is a sequence of characters, so `for ch in word` works exactly like looping over a list — no need to index into it with `word[i]`.',
  },
  {
    id: 'nested-loop-over-pairs',
    task: 'Loop over every pair from two lists',
    group: 'loops',
    also: ['nested loop', 'combinations', 'grid'],
    topicId: 'while-nested-loops',
    code: "colours = ['red', 'blue']\nsizes = ['S', 'M']\nfor c in colours:\n    for s in sizes:\n        print(c, s)\n",
    note: 'The inner loop runs completely for every single pass of the outer loop, so two lists of length 2 give 4 pairs, and lengths `m` and `n` give `m * n`.',
  },
  {
    id: 'count-matches-in-a-loop',
    task: 'Count how many items in a loop match a condition',
    group: 'loops',
    also: ['count if', 'tally', 'how many match'],
    topicId: 'for-loops-range',
    code: "marks = [72, 45, 91, 38, 68]\npasses = 0\nfor m in marks:\n    if m >= 50:\n        passes += 1\nprint(passes)\n",
    note: 'This is the same accumulator pattern as a running total, except each pass adds either 0 or 1 depending on the condition instead of adding the value itself.',
  },
];

export default recipes;
