// Reference: text.
import type { Recipe } from '../recipeSchema.ts';

const recipes: Recipe[] = [
  {
    id: 'slice-a-string',
    task: 'Take a piece out of a string',
    group: 'text',
    also: ['slicing', 'substring', 'first n characters', 'last n characters'],
    topicId: 'strings',
    code: "word = 'programming'\nprint(word[:4])\nprint(word[-3:])\nprint(word[2:6])\n",
    note: 'A slice `s[start:stop]` never raises even when the numbers run past the ends of the string; it just stops at whatever is there.',
  },
  {
    id: 'reverse-a-string',
    task: 'Reverse a string',
    group: 'text',
    also: ['backwards', 'flip'],
    topicId: 'strings',
    code: "word = 'python'\nprint(word[::-1])\n",
    note: 'The slice `[::-1]` means "step backwards through the whole thing", which is the shortest way to reverse any sequence, not only a string.',
  },
  {
    id: 'case-insensitive-compare',
    task: 'Compare two strings ignoring upper and lower case',
    group: 'text',
    also: ['upper', 'lower', 'case sensitive'],
    topicId: 'strings',
    code: "a = 'Perth'\nb = 'PERTH'\nprint(a == b)\nprint(a.lower() == b.lower())\n",
    note: '`==` on strings is always case sensitive, so `\"Perth\" != \"PERTH\"`. Lower-casing both sides before comparing is the standard fix.',
  },
  {
    id: 'strip-whitespace',
    task: 'Remove leading and trailing whitespace from a string',
    group: 'text',
    also: ['strip', 'trim', 'whitespace'],
    topicId: 'strings',
    code: "raw = '  Ada Lovelace  \\n'\nprint(repr(raw.strip()))\nprint(repr(raw.lstrip()))\n",
    note: '`strip()` removes spaces, tabs and newlines from both ends only, never from the middle. `lstrip()`/`rstrip()` do just one end.',
  },
  {
    id: 'split-and-join',
    task: 'Split a string into parts and join them back together',
    group: 'text',
    also: ['split', 'join', 'parts', 'tokens'],
    topicId: 'strings',
    code: "line = 'apple, banana, cherry'\nparts = line.split(', ')\nprint(parts)\nprint('-'.join(parts))\n",
    note: '`split()` with no argument at all splits on any run of whitespace, which is handy for text with uneven spacing; give it a string like `\", \"` to split on something exact.',
  },
  {
    id: 'replace-part-of-a-string',
    task: 'Replace part of a string with something else',
    group: 'text',
    also: ['replace', 'substitute'],
    topicId: 'strings',
    code: "msg = 'see spot run'\nprint(msg.replace('spot', 'fido'))\nprint(msg)\n",
    note: 'Strings are immutable, so `.replace()` returns a new string and leaves `msg` untouched; you have to assign the result if you want to keep it.',
  },
  {
    id: 'starts-or-ends-with',
    task: 'Check what a string starts or ends with',
    group: 'text',
    also: ['startswith', 'endswith', 'prefix', 'suffix'],
    topicId: 'strings',
    code: "name = 'report_final.csv'\nprint(name.startswith('report'))\nprint(name.endswith('.csv'))\n",
    note: '`startswith`/`endswith` beat slicing to compare the start or end of a string: they read clearly and never raise, even on a short string.',
  },
  {
    id: 'find-inside-a-string',
    task: 'Find whether one string is inside another',
    group: 'text',
    also: ['contains', 'substring search', 'in'],
    topicId: 'strings',
    code: "sentence = 'the quick brown fox'\nprint('quick' in sentence)\nprint(sentence.find('slow'))\n",
    note: '`in` gives a plain `True`/`False`. `.find()` gives the index where the match starts, or `-1` when it is not there — never `-1` and `True` mixed up in the same check.',
  },
  {
    id: 'check-if-string-is-a-number',
    task: 'Check if a string looks like a number',
    group: 'text',
    also: ['isdigit', 'isnumeric', 'validate'],
    topicId: 'strings',
    code: "for text in ['42', '-3', '4.5']:\n    print(text, text.lstrip('-').replace('.', '', 1).isdigit())\n",
    note: '`str.isdigit()` alone is `False` for `\"-3\"` and `\"4.5\"` because it only recognises plain digits; a real check usually strips a leading sign and one decimal point first, or just tries `float(text)` in a `try`.',
  },
  {
    id: 'build-a-string-in-a-loop',
    task: 'Build up a string piece by piece in a loop',
    group: 'text',
    also: ['concatenate', 'accumulate string'],
    topicId: 'for-loops-range',
    code: "names = ['Ada', 'Bo', 'Cy']\nline = ''\nfor name in names:\n    line += name + ', '\nprint(line.rstrip(', '))\n",
    note: 'Adding to a string in a loop with `+=` works fine for a handful of pieces; for a lot of pieces, building a list and calling `\", \".join(list)` once is faster and usually clearer.',
  },
  {
    id: 'pad-or-align-text',
    task: 'Pad or align text to a fixed width',
    group: 'text',
    also: ['padding', 'align', 'columns', 'ljust', 'rjust'],
    code: "for name in ['Ada', 'Bo']:\n    print(f'{name:<8}|{len(name):>3}')\n",
    note: 'Inside an f-string, `{value:<8}` left-aligns to a width of 8 and `{value:>3}` right-aligns to 3; the same characters work outside f-strings as `s.ljust(8)` and `s.rjust(3)`.',
  },
];

export default recipes;
