// Cheat sheet, worked example and common mistakes for topic 03 (for loops and range).
import type { Topic } from '../../schema.ts';

export const cheatsheet: Topic['cheatsheet'] = [
  '**range() at a glance**',
  '',
  '```python',
  'range(5)            # 0, 1, 2, 3, 4      start defaults to 0',
  'range(2, 6)         # 2, 3, 4, 5         the stop value is never included',
  'range(1, 10, 3)     # 1, 4, 7            step of 3',
  'range(10, 0, -2)    # 10, 8, 6, 4, 2     a negative step counts down',
  'range(5, 5)         # nothing            the loop body never runs',
  'range(5, 1)         # nothing            a positive step cannot count down',
  '```',
  '',
  '- `range(a, b)` gives `b - a` values when `b > a`.',
  '- To include `n`, add one to the stop: `range(1, n + 1)`. Counting down to 1 needs `range(n, 0, -1)`.',
  '- All three arguments must be ints. `range(0, 1, 0.5)` raises `TypeError`, and a step of 0 raises `ValueError`.',
  '- To see the values in the Thonny shell, type `list(range(2, 15, 2))`.',
  '',
  '**The for loop**',
  '',
  '```python',
  'for day in range(1, 4):',
  "    print('Day', day)     # indented: runs on every pass",
  "print('Done')            # not indented: runs once, after the loop",
  '```',
  '',
  '- The header ends with a colon, and the body is indented 4 spaces.',
  '- At the start of every pass the loop variable takes the next value from the range. Changing it inside the body does not skip values; use the step instead.',
  '- After the loop the variable keeps its last value (3 above). If the range was empty, the body never runs and the loop variable is not given a value at all.',
  '',
  '**Accumulators: set up once, before the loop**',
  '',
  '```python',
  'n = 6',
  'total = 0        # a sum starts at 0',
  'product = 1      # a product starts at 1 (0 would make every answer 0)',
  'count = 0        # a count starts at 0',
  'for k in range(1, n + 1):',
  '    total = total + k        # same as total += k',
  '    product = product * k',
  '    if k % 3 == 0:           # loop + if: count only some values',
  '        count = count + 1',
  'print(total, product, count)   # 21 720 2',
  '```',
  '',
  '- Setting `total = 0` inside the loop restarts it on every pass, so only the last pass counts.',
  '- Name it `total`, not `sum`: `sum`, `max` and `min` are built-in functions.',
  '',
  '**Reading n values with input()**',
  '',
  '```python',
  'n = int(input())',
  'total = 0',
  'for i in range(n):',
  '    temp = float(input())    # float, because int("36.5") raises ValueError',
  '    total = total + temp',
  'print(round(total / n, 1))   # after the loop, so it prints once',
  '```',
  '',
  '**Two variables changing together (Fibonacci)**',
  '',
  '```python',
  'this_fib, next_fib = 1, 1',
  'for i in range(6):',
  '    print(this_fib)          # 1, 1, 2, 3, 5, 8',
  '    this_fib, next_fib = next_fib, this_fib + next_fib',
  '```',
  '',
  'The right-hand side is worked out in full, using the OLD values, before either name changes. Splitting the last line into `this_fib = next_fib` then `next_fib = this_fib + next_fib` is wrong: the second line would use the new `this_fib`.',
  '',
  '**return inside a loop**',
  '',
  '```python',
  'def first_multiple(start, stop, k):',
  '    for n in range(start, stop):',
  '        if n % k == 0:',
  '            return n         # found it: stop straight away',
  '    return 0                 # not found: only after checking every value',
  '```',
  '',
  '- A `return` in an `else` inside the loop gives up after the first value.',
  '',
  '**Tracing a loop by hand**',
  '',
  '1. Write the range values first, so you know how many rows there are.',
  '2. One row per pass. Work each line in order and write the new values.',
  '3. Check the edge cases: the loop runs 0 times, once, and many times.',
].join('\n');

export const workedExample: Topic['workedExample'] = {
  title: 'City to Surf: counting stops on the course',
  code: [
    'def count_stops(distance):',
    '    """Return how many km markers from 1 to distance have a drink station or first-aid tent."""',
    '    count = 0',
    '    for km in range(1, distance + 1):',
    '        if km % 3 == 0 or km % 5 == 0:',
    '            count = count + 1',
    '    return count',
    '',
    '',
    'print(count_stops(12))   # stops at 3, 5, 6, 9, 10, 12, so this prints 6',
  ].join('\n'),
  steps: [
    '**The problem.** The Perth City to Surf course has a marker at every whole kilometre. There is a drink station at every marker that is a multiple of 3 and a first-aid tent at every multiple of 5. Write `count_stops(distance)` that returns how many markers from 1 to `distance` (inclusive) have a drink station, a first-aid tent, or both.',
    '**Work an example by hand.** For 12 km the stops are at 3, 5, 6, 9, 10 and 12, so the answer is 6. Marker 15 has both and must count once. The smallest case, `count_stops(0)`, should return 0.',
    '**Pick the loop values.** We need markers 1, 2, ..., `distance`. range stops before its stop value, so the header is `for km in range(1, distance + 1):`. With `range(1, distance)` the last marker would never be checked.',
    '**Set up the counter before the loop.** `count = 0` goes above the `for` line so it is set once. If it were inside the loop it would go back to 0 on every pass.',
    '**Decide inside the loop.** A marker counts when `km % 3 == 0 or km % 5 == 0`. One `if` with `or` counts marker 15 once; two separate `if` statements that each add 1 would count it twice.',
    '**Return after the loop, then check.** `return count` lines up with `for`, so it runs once every marker has been checked. Trace distance 6: km 3 makes count 1, km 5 makes 2, km 6 makes 3, so the function returns 3, which matches a hand count. With distance 0 the range is empty and the function returns 0.',
  ],
};

export const commonMistakes: Topic['commonMistakes'] = [
  {
    mistake: 'off_by_one_range',
    bad: 'total = 0\nfor k in range(1, n):\n    total = total + k',
    good: 'total = 0\nfor k in range(1, n + 1):\n    total = total + k',
    note: '`range(1, n)` stops at `n - 1`. When the task says "from 1 to n", add one to the stop. Check the first and last values the loop really produces.',
  },
  {
    mistake: 'accumulator_init',
    bad: 'for day in range(7):\n    hot_days = 0\n    temp = float(input())\n    if temp >= 35:\n        hot_days = hot_days + 1',
    good: 'hot_days = 0\nfor day in range(7):\n    temp = float(input())\n    if temp >= 35:\n        hot_days = hot_days + 1',
    note: 'A total or count is set once, before the loop. Inside the loop it restarts on every pass. Sums and counts start at 0; products start at 1.',
  },
  {
    mistake: 'modify_loop_var',
    bad: 'for seat in range(1, 10):\n    print(seat)\n    seat = seat + 2   # does not skip anything',
    good: 'for seat in range(1, 10, 3):\n    print(seat)       # 1, 4, 7',
    note: 'The `for` line hands the loop variable its next value on every pass, whatever the body did to it. To jump in steps, give range a step.',
  },
  {
    mistake: 'early_return_in_loop',
    bad: 'def has_multiple(start, stop, k):\n    for n in range(start, stop):\n        if n % k == 0:\n            return True\n        else:\n            return False',
    good: 'def has_multiple(start, stop, k):\n    for n in range(start, stop):\n        if n % k == 0:\n            return True\n    return False',
    note: '`return` ends the function at once. Return inside the loop only when you have found the answer; the "not found" return goes after the loop.',
  },
  {
    mistake: 'indent_error',
    bad: 'total = 0\nfor day in range(1, 8):\n    total = total + day\n    print(total)',
    good: 'total = 0\nfor day in range(1, 8):\n    total = total + day\nprint(total)',
    note: 'Indentation decides whether a line runs on every pass or once after the loop. A result that should be printed once goes back at the same level as `for`.',
  },
  {
    mistake: 'shadow_builtin',
    bad: 'sum = 0\nfor k in range(1, 6):\n    sum = sum + k',
    good: 'total = 0\nfor k in range(1, 6):\n    total = total + k',
    note: 'Calling a variable `sum`, `max` or `min` hides the built-in function with that name for the rest of the program. Use names like `total` and `highest`.',
  },
];
