// The glossary. One entry per word a first-year meets before anyone defines it for them.
//
// Definitions are written for someone who does not already know the word. Where a term is a claim about
// Python's behaviour, `demo` carries code that shows it and the verifier runs that code for the output.
import type { Term } from './glossarySchema.ts';

export const TERMS: Term[] = [
  {
    id: 'argument',
    term: 'argument',
    also: ['arguments', 'args', 'pass in'],
    short: 'The actual value you hand to a function when you call it.',
    note: 'The value is the argument; the name it arrives under inside the function is the [[parameter]].',
    confusedWith: 'parameter',
    lessonId: 'core-functions',
    demo: 'def greet(name):\n    print("Hello,", name)\n\n# "Perth" is the argument\ngreet("Perth")\n',
  },
  {
    id: 'parameter',
    term: 'parameter',
    also: ['parameters', 'formal parameter'],
    short: 'The name a function gives to a value it is handed, written in its def line.',
    note: 'A parameter is a name waiting for a value; an [[argument]] is the value that turns up.',
    confusedWith: 'argument',
    lessonId: 'core-functions',
    demo: 'def area(width, height):\n    # width and height are the parameters\n    return width * height\n\nprint(area(3, 4))\n',
  },
  {
    id: 'return',
    term: 'return',
    also: ['returns', 'returning', 'return value'],
    short: 'Hands a value back to whoever called the function, and stops the function there.',
    note: 'Returning is not printing. A function that prints shows you something; a function that returns gives you something you can use.',
    confusedWith: 'print',
    lessonId: 'core-functions',
    demo: 'def double(n):\n    return n * 2\n\nresult = double(21)\nprint(result)\nprint(double(5) + 1)\n',
  },
  {
    id: 'print',
    term: 'print',
    also: ['printing', 'prints', 'output'],
    short: 'Writes something on the screen for a person to read.',
    note: 'A function that prints instead of returning gives the caller nothing: the call is worth None.',
    confusedWith: 'return',
    lessonId: 'showing-your-work',
    demo: 'def shows(n):\n    print(n * 2)\n\nvalue = shows(21)\nprint("the call was worth:", value)\n',
  },
  {
    id: 'none',
    term: 'None',
    also: ['null', 'nothing', 'returns nothing'],
    short: 'Python\'s word for "no value at all".',
    note: 'A function with no return statement hands back None, which is why printing its result shows None.',
    lessonId: 'core-functions',
    demo: 'def nothing():\n    pass\n\nprint(nothing())\nprint(None is None)\n',
  },
  {
    id: 'mutable',
    term: 'mutable',
    also: ['mutate', 'mutation', 'changeable'],
    short: 'Able to be changed after it is made. Lists, dictionaries and sets are mutable.',
    note: 'Changing a mutable value changes it for every name pointing at it — see [[aliasing]].',
    confusedWith: 'immutable',
    lessonId: 'mutability-and-copying',
    demo: 'prices = [3, 5]\nprices.append(7)\nprint(prices)\n',
  },
  {
    id: 'immutable',
    term: 'immutable',
    also: ['unchangeable', 'cannot be changed'],
    short: 'Cannot be changed once made. Strings, numbers and tuples are immutable.',
    note: 'Operations that look like changes build a new value instead and leave the old one alone.',
    confusedWith: 'mutable',
    lessonId: 'core-strings',
    demo: 'name = "perth"\nupper = name.upper()\nprint(name)\nprint(upper)\n',
  },
  {
    id: 'aliasing',
    term: 'aliasing',
    also: ['alias', 'same list', 'two names'],
    short: 'Two names pointing at the same value, so a change through one shows through the other.',
    note: 'Assigning a list to a second name does not copy it. Use list(...) or a slice to get a copy.',
    lessonId: 'mutability-and-copying',
    demo: 'a = [1, 2]\nb = a\nb.append(3)\nprint(a)\nprint(a is b)\n',
  },
  {
    id: 'index',
    term: 'index',
    also: ['indices', 'position', 'subscript'],
    short: 'The position of an item in a list or string, counting from 0.',
    note: 'The last item is at index len(x) - 1, which is why len(x) itself is out of range.',
    lessonId: 'core-lists-tuples',
    demo: 'days = ["Mon", "Tue", "Wed"]\nprint(days[0])\nprint(days[-1])\nprint(len(days))\n',
  },
  {
    id: 'slice',
    term: 'slice',
    also: ['slicing', 'sublist', 'substring'],
    short: 'A piece of a list or string, written x[start:stop].',
    note: 'The stop position is not included, so x[0:2] gives two items.',
    lessonId: 'core-strings',
    demo: 'word = "Fremantle"\nprint(word[0:4])\nprint(word[:3])\nprint(word[-3:])\n',
  },
  {
    id: 'tuple',
    term: 'tuple',
    also: ['tuples', 'pair', 'fixed list'],
    short: 'A fixed sequence of values, written with round brackets: (1, 2).',
    note: 'Like a list but immutable, which makes it safe to use as a dictionary key.',
    lessonId: 'core-lists-tuples',
    demo: 'point = (3, 4)\nx, y = point\nprint(x, y)\nprint(len(point))\n',
  },
  {
    id: 'key',
    term: 'key',
    also: ['keys', 'lookup'],
    short: 'The thing you look something up by in a dictionary.',
    note: 'Asking for a key that is not there raises KeyError; .get() returns None instead.',
    lessonId: 'core-dictionaries',
    demo: 'ages = {"ada": 36}\nprint(ages["ada"])\nprint(ages.get("bob"))\n',
  },
  {
    id: 'iterate',
    term: 'iterate',
    also: ['iterating', 'loop over', 'iterable', 'traverse'],
    short: 'To go through something one item at a time, which is what a for loop does.',
    note: 'Looping over a dictionary gives you its keys, not its values.',
    lessonId: 'core-for-loops',
    demo: 'for letter in "abc":\n    print(letter)\n\nfor key in {"a": 1, "b": 2}:\n    print(key)\n',
  },
  {
    id: 'accumulator',
    term: 'accumulator',
    also: ['running total', 'build up', 'total'],
    short: 'A variable you set up before a loop and add to inside it.',
    note: 'It has to be created before the loop starts, or the first pass has nothing to add to.',
    lessonId: 'core-for-loops',
    demo: 'total = 0\nfor n in [2, 4, 6]:\n    total = total + n\nprint(total)\n',
  },
  {
    id: 'expression',
    term: 'expression',
    also: ['expressions', 'evaluates'],
    short: 'A piece of code that produces a value: 2 + 2, name.upper(), x > 3.',
    confusedWith: 'statement',
    lessonId: 'doing-arithmetic',
    demo: 'print(2 + 2)\nprint("ab" * 3)\nprint(5 > 3)\n',
  },
  {
    id: 'statement',
    term: 'statement',
    also: ['statements', 'line of code'],
    short: 'A complete instruction: an assignment, an if, a loop, a return.',
    note: 'An expression produces a value; a statement does something.',
    confusedWith: 'expression',
    lessonId: 'what-a-program-is',
  },
  {
    id: 'boolean',
    term: 'boolean',
    also: ['bool', 'true', 'false', 'truthy', 'falsy'],
    short: 'A value that is either True or False.',
    note: 'Python also treats 0, "" and [] as false when it needs a yes or no, which is what "falsy" means.',
    lessonId: 'core-decisions',
    demo: 'print(3 > 5)\nprint(bool(0), bool(""), bool([]))\nprint(bool("no"), bool([0]))\n',
  },
  {
    id: 'float',
    term: 'float',
    also: ['floats', 'decimal', 'floating point'],
    short: 'A number with a decimal point, like 3.5.',
    note: 'Floats are stored in binary, so some sums come out a hair off: 0.1 + 0.2 is not exactly 0.3.',
    lessonId: 'values-and-types',
    demo: 'print(0.1 + 0.2)\nprint(7 / 2)\nprint(round(2.675, 2))\n',
  },
  {
    id: 'integer',
    term: 'integer',
    also: ['int', 'whole number'],
    short: 'A whole number, with no decimal point.',
    note: 'Dividing with / always gives a float; // keeps it whole and rounds down.',
    lessonId: 'values-and-types',
    demo: 'print(7 / 2)\nprint(7 // 2)\nprint(-7 // 2)\n',
  },
  {
    id: 'concatenate',
    term: 'concatenate',
    also: ['concatenation', 'join strings', 'stick together'],
    short: 'To join two strings end to end with +.',
    note: 'Both sides have to be strings: adding a number raises TypeError unless you convert it first.',
    lessonId: 'core-strings',
    demo: 'first = "Swan"\nprint(first + " River")\nprint(first + str(2))\n',
  },
  {
    id: 'method',
    term: 'method',
    also: ['methods', 'dot call'],
    short: 'A function that belongs to a value, called with a dot: name.upper().',
    note: 'A method acts on the thing before the dot, which is why it needs no argument for it.',
    confusedWith: 'function',
    lessonId: 'core-strings',
    demo: 'name = "  perth  "\nprint(name.strip().title())\nprint("a,b".split(","))\n',
  },
  {
    id: 'function',
    term: 'function',
    also: ['functions', 'def'],
    short: 'A named block of code you can run whenever you want, by calling it.',
    confusedWith: 'method',
    lessonId: 'core-functions',
    demo: 'def shout(word):\n    return word.upper() + "!"\n\nprint(shout("hey"))\n',
  },
  {
    id: 'scope',
    term: 'scope',
    also: ['local', 'global', 'visible'],
    short: 'Where a name can be seen. A name made inside a function is only visible inside it.',
    note: 'That is why a variable made in a function vanishes when the function ends.',
    lessonId: 'core-scope-and-main',
    demo: 'def f():\n    inside = 1\n    print("inside sees:", inside)\n\nf()\nprint("outside sees:", "inside" in dir())\n',
  },
  {
    id: 'traceback',
    term: 'traceback',
    also: ['stack trace', 'error message', 'red text'],
    short: 'The report Python prints when something goes wrong, listing where it happened.',
    note: 'Read it from the bottom: the last line names the error, and the line above it is usually your code.',
    lessonId: 'reading-an-error',
  },
  {
    id: 'exception',
    term: 'exception',
    also: ['exceptions', 'raise', 'error'],
    short: 'Python\'s way of stopping when it cannot carry on, like dividing by zero.',
    note: 'try/except lets you catch one and decide what to do instead of stopping.',
    lessonId: 'core-exceptions',
    demo: 'try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print("caught it")\n',
  },
  {
    id: 'syntax',
    term: 'syntax',
    also: ['syntax error', 'grammar'],
    short: 'The grammar of the language: where the colons, brackets and indents go.',
    note: 'A SyntaxError means Python could not read the code at all, so nothing ran — not even the lines above it.',
    lessonId: 'reading-an-error',
  },
  {
    id: 'indentation',
    term: 'indentation',
    also: ['indent', 'whitespace', 'spaces'],
    short: 'The spaces at the start of a line, which is how Python knows what is inside what.',
    note: 'Four spaces per level is the convention. Mixing tabs and spaces is a common cause of errors.',
    lessonId: 'what-a-program-is',
  },
  {
    id: 'base-case',
    term: 'base case',
    also: ['stopping case', 'recursion stop'],
    short: 'The case a recursive function answers directly, without calling itself again.',
    note: 'Without one the calls never stop, and Python gives up with RecursionError.',
    lessonId: 'core-recursion',
    demo: 'def countdown(n):\n    if n == 0:\n        return "liftoff"\n    return countdown(n - 1)\n\nprint(countdown(3))\n',
  },
  {
    id: 'recursion',
    term: 'recursion',
    also: ['recursive', 'calls itself'],
    short: 'A function that calls itself on a smaller version of the same problem.',
    note: 'Every recursive function needs a [[base-case]] or it never stops.',
    lessonId: 'core-recursion',
    demo: 'def total(nums):\n    if not nums:\n        return 0\n    return nums[0] + total(nums[1:])\n\nprint(total([1, 2, 3]))\n',
  },
  {
    id: 'signature',
    term: 'signature',
    also: ['def line', 'header'],
    short: 'The def line of a function: its name and the parameters it takes.',
    note: 'A project brief that fixes a signature means calling it that exact way, with that many parameters.',
    lessonId: 'core-functions',
  },
  {
    id: 'literal',
    term: 'literal',
    also: ['literals', 'written out'],
    short: 'A value written directly in the code: 42, "hello", [1, 2].',
    lessonId: 'values-and-types',
  },
  {
    id: 'operand',
    term: 'operand',
    also: ['operands', 'either side'],
    short: 'A value an operator works on. In 2 + 3, the operands are 2 and 3.',
    lessonId: 'doing-arithmetic',
  },
  {
    id: 'nested',
    term: 'nested',
    also: ['nesting', 'inside another'],
    short: 'One thing inside another: a loop inside a loop, or a list inside a list.',
    note: 'A nested loop runs its whole inner loop for every single pass of the outer one.',
    lessonId: 'core-while-loops',
    demo: 'for a in [1, 2]:\n    for b in ["x", "y"]:\n        print(a, b)\n',
  },
];
