// The glossary. One entry per word a first-year meets before anyone defines it for them.
//
// Definitions are written for someone who does not already know the word. Where a term is a claim about
// Python's behaviour, `demo` carries code that shows it and the verifier runs that code for the output.
import type { Term } from './glossarySchema.ts';

export const TERMS: Term[] = [
  {
    id: 'argument',
    term: 'argument',
    also: ['arguments', 'args', 'pass in'],
    short: 'The actual value you hand to a function when you call it.',
    note: 'The value is the argument; the name it arrives under inside the function is the [[parameter]].',
    confusedWith: 'parameter',
    lessonId: 'core-functions',
    demo: 'def greet(name):\n    print("Hello,", name)\n\n# "Perth" is the argument\ngreet("Perth")\n',
  },
  {
    id: 'parameter',
    term: 'parameter',
    also: ['parameters', 'formal parameter'],
    short: 'The name a function gives to a value it is handed, written in its def line.',
    note: 'A parameter is a name waiting for a value; an [[argument]] is the value that turns up.',
    confusedWith: 'argument',
    lessonId: 'core-functions',
    demo: 'def area(width, height):\n    # width and height are the parameters\n    return width * height\n\nprint(area(3, 4))\n',
  },
  {
    id: 'return',
    term: 'return',
    also: ['returns', 'returning', 'return value'],
    short: 'Hands a value back to whoever called the function, and stops the function there.',
    note: 'Returning is not printing. A function that prints shows you something; a function that returns gives you something you can use.',
    confusedWith: 'print',
    lessonId: 'core-functions',
    demo: 'def double(n):\n    return n * 2\n\nresult = double(21)\nprint(result)\nprint(double(5) + 1)\n',
  },
  {
    id: 'print',
    term: 'print',
    also: ['printing', 'prints', 'output'],
    short: 'Writes something on the screen for a person to read.',
    note: 'A function that prints instead of returning gives the caller nothing: the call is worth None.',
    confusedWith: 'return',
    lessonId: 'showing-your-work',
    demo: 'def shows(n):\n    print(n * 2)\n\nvalue = shows(21)\nprint("the call was worth:", value)\n',
  },
  {
    id: 'none',
    term: 'None',
    also: ['null', 'nothing', 'returns nothing'],
    short: 'Python\'s word for "no value at all".',
    note: 'A function with no return statement hands back None, which is why printing its result shows None.',
    lessonId: 'core-functions',
    demo: 'def nothing():\n    pass\n\nprint(nothing())\nprint(None is None)\n',
  },
  {
    id: 'mutable',
    term: 'mutable',
    also: ['mutate', 'mutation', 'changeable'],
    short: 'Able to be changed after it is made. Lists, dictionaries and sets are mutable.',
    note: 'Changing a mutable value changes it for every name pointing at it — see [[aliasing]].',
    confusedWith: 'immutable',
    lessonId: 'mutability-and-copying',
    demo: 'prices = [3, 5]\nprices.append(7)\nprint(prices)\n',
  },
  {
    id: 'immutable',
    term: 'immutable',
    also: ['unchangeable', 'cannot be changed'],
    short: 'Cannot be changed once made. Strings, numbers and tuples are immutable.',
    note: 'Operations that look like changes build a new value instead and leave the old one alone.',
    confusedWith: 'mutable',
    lessonId: 'core-strings',
    demo: 'name = "perth"\nupper = name.upper()\nprint(name)\nprint(upper)\n',
  },
  {
    id: 'aliasing',
    term: 'aliasing',
    also: ['alias', 'same list', 'two names'],
    short: 'Two names pointing at the same value, so a change through one shows through the other.',
    note: 'Assigning a list to a second name does not copy it. Use list(...) or a slice to get a copy.',
    lessonId: 'mutability-and-copying',
    demo: 'a = [1, 2]\nb = a\nb.append(3)\nprint(a)\nprint(a is b)\n',
  },
  {
    id: 'index',
    term: 'index',
    also: ['indices', 'position', 'subscript'],
    short: 'The position of an item in a list or string, counting from 0.',
    note: 'The last item is at index len(x) - 1, which is why len(x) itself is out of range.',
    lessonId: 'core-lists-tuples',
    demo: 'days = ["Mon", "Tue", "Wed"]\nprint(days[0])\nprint(days[-1])\nprint(len(days))\n',
  },
  {
    id: 'slice',
    term: 'slice',
    also: ['slicing', 'sublist', 'substring'],
    short: 'A piece of a list or string, written x[start:stop].',
    note: 'The stop position is not included, so x[0:2] gives two items.',
    lessonId: 'core-strings',
    demo: 'word = "Fremantle"\nprint(word[0:4])\nprint(word[:3])\nprint(word[-3:])\n',
  },
  {
    id: 'tuple',
    term: 'tuple',
    also: ['tuples', 'pair', 'fixed list'],
    short: 'A fixed sequence of values, written with round brackets: (1, 2).',
    note: 'Like a list but immutable, which makes it safe to use as a dictionary key.',
    lessonId: 'core-lists-tuples',
    demo: 'point = (3, 4)\nx, y = point\nprint(x, y)\nprint(len(point))\n',
  },
  {
    id: 'key',
    term: 'key',
    also: ['keys', 'lookup'],
    short: 'The thing you look something up by in a dictionary.',
    note: 'Asking for a key that is not there raises KeyError; .get() returns None instead.',
    lessonId: 'core-dictionaries',
    demo: 'ages = {"ada": 36}\nprint(ages["ada"])\nprint(ages.get("bob"))\n',
  },
  {
    id: 'iterate',
    term: 'iterate',
    also: ['iterating', 'loop over', 'iterable', 'traverse'],
    short: 'To go through something one item at a time, which is what a for loop does.',
    note: 'Looping over a dictionary gives you its keys, not its values.',
    lessonId: 'core-for-loops',
    demo: 'for letter in "abc":\n    print(letter)\n\nfor key in {"a": 1, "b": 2}:\n    print(key)\n',
  },
  {
    id: 'accumulator',
    term: 'accumulator',
    also: ['running total', 'build up', 'total'],
    short: 'A variable you set up before a loop and add to inside it.',
    note: 'It has to be created before the loop starts, or the first pass has nothing to add to.',
    lessonId: 'core-for-loops',
    demo: 'total = 0\nfor n in [2, 4, 6]:\n    total = total + n\nprint(total)\n',
  },
  {
    id: 'expression',
    term: 'expression',
    also: ['expressions', 'evaluates'],
    short: 'A piece of code that produces a value: 2 + 2, name.upper(), x > 3.',
    confusedWith: 'statement',
    lessonId: 'doing-arithmetic',
    demo: 'print(2 + 2)\nprint("ab" * 3)\nprint(5 > 3)\n',
  },
  {
    id: 'statement',
    term: 'statement',
    also: ['statements', 'line of code'],
    short: 'A complete instruction: an assignment, an if, a loop, a return.',
    note: 'An expression produces a value; a statement does something.',
    confusedWith: 'expression',
    lessonId: 'what-a-program-is',
  },
  {
    id: 'boolean',
    term: 'boolean',
    also: ['bool', 'true', 'false', 'truthy', 'falsy'],
    short: 'A value that is either True or False.',
    note: 'Python also treats 0, "" and [] as false when it needs a yes or no, which is what "falsy" means.',
    lessonId: 'core-decisions',
    demo: 'print(3 > 5)\nprint(bool(0), bool(""), bool([]))\nprint(bool("no"), bool([0]))\n',
  },
  {
    id: 'float',
    term: 'float',
    also: ['floats', 'decimal', 'floating point'],
    short: 'A number with a decimal point, like 3.5.',
    note: 'Floats are stored in binary, so some sums come out a hair off: 0.1 + 0.2 is not exactly 0.3.',
    lessonId: 'values-and-types',
    demo: 'print(0.1 + 0.2)\nprint(7 / 2)\nprint(round(2.675, 2))\n',
  },
  {
    id: 'integer',
    term: 'integer',
    also: ['int', 'whole number'],
    short: 'A whole number, with no decimal point.',
    note: 'Dividing with / always gives a float; // keeps it whole and rounds down.',
    lessonId: 'values-and-types',
    demo: 'print(7 / 2)\nprint(7 // 2)\nprint(-7 // 2)\n',
  },
  {
    id: 'concatenate',
    term: 'concatenate',
    also: ['concatenation', 'join strings', 'stick together'],
    short: 'To join two strings end to end with +.',
    note: 'Both sides have to be strings: adding a number raises TypeError unless you convert it first.',
    lessonId: 'core-strings',
    demo: 'first = "Swan"\nprint(first + " River")\nprint(first + str(2))\n',
  },
  {
    id: 'method',
    term: 'method',
    also: ['methods', 'dot call'],
    short: 'A function that belongs to a value, called with a dot: name.upper().',
    note: 'A method acts on the thing before the dot, which is why it needs no argument for it.',
    confusedWith: 'function',
    lessonId: 'core-strings',
    demo: 'name = "  perth  "\nprint(name.strip().title())\nprint("a,b".split(","))\n',
  },
  {
    id: 'function',
    term: 'function',
    also: ['functions', 'def'],
    short: 'A named block of code you can run whenever you want, by calling it.',
    confusedWith: 'method',
    lessonId: 'core-functions',
    demo: 'def shout(word):\n    return word.upper() + "!"\n\nprint(shout("hey"))\n',
  },
  {
    id: 'scope',
    term: 'scope',
    also: ['local', 'global', 'visible'],
    short: 'Where a name can be seen. A name made inside a function is only visible inside it.',
    note: 'That is why a variable made in a function vanishes when the function ends.',
    lessonId: 'core-scope-and-main',
    demo: 'def f():\n    inside = 1\n    print("inside sees:", inside)\n\nf()\nprint("outside sees:", "inside" in dir())\n',
  },
  {
    id: 'traceback',
    term: 'traceback',
    also: ['stack trace', 'error message', 'red text'],
    short: 'The report Python prints when something goes wrong, listing where it happened.',
    note: 'Read it from the bottom: the last line names the error, and the line above it is usually your code.',
    lessonId: 'reading-an-error',
  },
  {
    id: 'exception',
    term: 'exception',
    also: ['exceptions', 'raise', 'error'],
    short: 'Python\'s way of stopping when it cannot carry on, like dividing by zero.',
    note: 'try/except lets you catch one and decide what to do instead of stopping.',
    lessonId: 'core-exceptions',
    demo: 'try:\n    print(1 / 0)\nexcept ZeroDivisionError:\n    print("caught it")\n',
  },
  {
    id: 'syntax',
    term: 'syntax',
    also: ['syntax error', 'grammar'],
    short: 'The grammar of the language: where the colons, brackets and indents go.',
    note: 'A SyntaxError means Python could not read the code at all, so nothing ran — not even the lines above it.',
    lessonId: 'reading-an-error',
  },
  {
    id: 'indentation',
    term: 'indentation',
    also: ['indent', 'whitespace', 'spaces'],
    short: 'The spaces at the start of a line, which is how Python knows what is inside what.',
    note: 'Four spaces per level is the convention. Mixing tabs and spaces is a common cause of errors.',
    lessonId: 'what-a-program-is',
  },
  {
    id: 'base-case',
    term: 'base case',
    also: ['stopping case', 'recursion stop'],
    short: 'The case a recursive function answers directly, without calling itself again.',
    note: 'Without one the calls never stop, and Python gives up with RecursionError.',
    lessonId: 'core-recursion',
    demo: 'def countdown(n):\n    if n == 0:\n        return "liftoff"\n    return countdown(n - 1)\n\nprint(countdown(3))\n',
  },
  {
    id: 'recursion',
    term: 'recursion',
    also: ['recursive', 'calls itself'],
    short: 'A function that calls itself on a smaller version of the same problem.',
    note: 'Every recursive function needs a [[base-case]] or it never stops.',
    lessonId: 'core-recursion',
    demo: 'def total(nums):\n    if not nums:\n        return 0\n    return nums[0] + total(nums[1:])\n\nprint(total([1, 2, 3]))\n',
  },
  {
    id: 'signature',
    term: 'signature',
    also: ['def line', 'header'],
    short: 'The def line of a function: its name and the parameters it takes.',
    note: 'A project brief that fixes a signature means calling it that exact way, with that many parameters.',
    lessonId: 'core-functions',
  },
  {
    id: 'literal',
    term: 'literal',
    also: ['literals', 'written out'],
    short: 'A value written directly in the code: 42, "hello", [1, 2].',
    lessonId: 'values-and-types',
  },
  {
    id: 'operand',
    term: 'operand',
    also: ['operands', 'either side'],
    short: 'A value an operator works on. In 2 + 3, the operands are 2 and 3.',
    lessonId: 'doing-arithmetic',
  },
  {
    id: 'nested',
    term: 'nested',
    also: ['nesting', 'inside another'],
    short: 'One thing inside another: a loop inside a loop, or a list inside a list.',
    note: 'A nested loop runs its whole inner loop for every single pass of the outer one.',
    lessonId: 'core-while-loops',
    demo: 'for a in [1, 2]:\n    for b in ["x", "y"]:\n        print(a, b)\n',
  },
  // ---------- Markets track: physical commodity trading. Listed only when it is switched on. ----------
  {
    id: 'spot',
    term: 'spot',
    also: ['spot price', 'prompt', 'cash price'],
    short: 'The price for a cargo delivered now, rather than on some date in the future.',
    note: 'Everything else prices off it: a forward is spot plus the cost of waiting, a differential is a premium or discount to it.',
    lessonId: 'what-a-barrel-is',
    markets: true,
  },
  {
    id: 'crude-grade',
    term: 'crude grade',
    also: ['grade', 'brent', 'wti', 'dubai', 'benchmark'],
    short: 'A named type of crude oil with its own chemistry and its own price, such as Brent, WTI or Dubai.',
    note: 'A barrel is not a barrel. Two cargoes at the same volume can be worth several dollars apart because of what comes out of them at the refinery.',
    lessonId: 'what-a-barrel-is',
    markets: true,
  },
  {
    id: 'api-gravity',
    term: 'API gravity',
    also: ['api', 'light crude', 'heavy crude', 'density'],
    short: 'How light or heavy a crude is. Higher API means lighter, and lighter usually means more petrol and diesel per barrel.',
    note: 'Light and sweet is the easy stuff; heavy and sour needs a more expensive refinery, which is why it trades at a discount.',
    lessonId: 'what-a-barrel-is',
    markets: true,
  },
  {
    id: 'sour',
    term: 'sour',
    also: ['sweet', 'sulphur', 'sour crude', 'sweet crude'],
    short: 'Crude with a lot of sulphur in it. Low sulphur is called sweet.',
    note: 'Sulphur has to be taken out before the fuel can be sold, so sour crude sells at a discount to sweet — the discount is roughly what removing it costs.',
    lessonId: 'what-a-barrel-is',
    markets: true,
  },
  {
    id: 'differential',
    term: 'differential',
    also: ['diff', 'premium to benchmark', 'discount to benchmark'],
    short: 'The premium or discount a particular cargo trades at against its benchmark grade.',
    note: 'Physical oil is almost never quoted as a flat price. It is quoted as the benchmark plus or minus a differential, and the differential is where a physical trader actually competes.',
    lessonId: 'what-a-barrel-is',
    markets: true,
  },
  {
    id: 'cargo',
    term: 'cargo',
    also: ['parcel', 'lot', 'shipment'],
    short: 'One shipload of a commodity, bought and sold as a single unit.',
    note: 'Crude usually moves in cargoes of 500,000 to 2 million barrels, which is why physical trading is a business of few, large, slow decisions.',
    lessonId: 'the-physical-chain',
    markets: true,
  },
  {
    id: 'forward-curve',
    term: 'forward curve',
    also: ['futures curve', 'term structure', 'the curve'],
    short: 'The prices quoted today for delivery in each future month, drawn as a line across those months.',
    note: 'Its shape is an instruction: upward ([[contango]]) pays you to store, downward ([[backwardation]]) pays you to sell now.',
    lessonId: 'the-storage-trade',
    markets: true,
  },
  {
    id: 'contango',
    term: 'contango',
    also: ['upward curve', 'later is dearer'],
    short: 'A forward curve that rises with time: oil for later delivery costs more than oil now.',
    note: 'The shape that fills tanks — but only where it is steeper than the [[carry]].',
    confusedWith: 'backwardation',
    lessonId: 'the-storage-trade',
    markets: true,
  },
  {
    id: 'backwardation',
    term: 'backwardation',
    also: ['downward curve', 'inverted curve', 'later is cheaper'],
    short: 'A forward curve that falls with time: oil now costs more than oil later.',
    note: 'The market saying it wants the barrel today. It empties storage, because holding stock means selling it forward for less than you paid.',
    confusedWith: 'contango',
    lessonId: 'the-storage-trade',
    markets: true,
  },
  {
    id: 'carry',
    term: 'carry',
    also: ['cost of carry', 'storage cost', 'financing cost'],
    short: 'Everything it costs to hold a barrel until a later date: tank rent, insurance, and interest on the money tied up in it.',
    note: 'The number a contango has to beat. On an $80 barrel at 5%, six months of financing alone is $2.',
    lessonId: 'the-storage-trade',
    markets: true,
  },
  {
    id: 'time-spread',
    term: 'time spread',
    also: ['calendar spread', 'spread between months'],
    short: 'The price difference between the same commodity for two different delivery months.',
    note: 'A storage trade is a bought time spread with a tank behind it: you own the near month and are short the far one.',
    lessonId: 'the-storage-trade',
    markets: true,
  },
  {
    id: 'freight',
    term: 'freight',
    also: ['shipping cost', 'charter', 'worldscale'],
    short: 'What it costs to move a cargo from one port to another, usually quoted per barrel or per tonne.',
    note: 'It is the toll on every location trade, and it moves on its own: a route can stop working because ships got expensive, with no change in the oil price at all.',
    lessonId: 'freight-and-the-arb',
    markets: true,
  },
  {
    id: 'location-spread',
    term: 'location spread',
    also: ['arb', 'arbitrage', 'regional spread', 'east-west'],
    short: 'The price difference for the same commodity in two places.',
    note: 'The arb is open when that gap is wider than the [[freight]] between them, and closed when it is not. Traders say "the arb is shut" to mean the cargo stays home.',
    lessonId: 'freight-and-the-arb',
    markets: true,
  },
  {
    id: 'vlcc',
    term: 'VLCC',
    also: ['very large crude carrier', 'supertanker', 'tanker'],
    short: 'A very large crude carrier: a tanker holding about two million barrels.',
    note: 'The standard unit of long-haul crude. When the curve is steep enough, traders hire them to sit still as floating storage.',
    lessonId: 'freight-and-the-arb',
    markets: true,
  },
  {
    id: 'spec',
    term: 'spec',
    also: ['specification', 'on-spec', 'off-spec', 'quality spec'],
    short: 'The quality a buyer has contracted for: limits on sulphur, density, flash point and the rest.',
    note: 'Miss one limit by a fraction and the cargo is off-spec, which can turn a premium product into a discounted one instantly.',
    lessonId: 'blending-to-spec',
    markets: true,
  },
  {
    id: 'blending',
    term: 'blending',
    also: ['blend', 'mixing', 'cutting'],
    short: 'Mixing two or more parcels so the result meets a specification neither of them met alone.',
    note: 'The classic asset-backed margin: buy the cheap off-spec barrel, blend it against something better, sell the mixture at the on-spec price.',
    lessonId: 'blending-to-spec',
    markets: true,
  },
  {
    id: 'crack-spread',
    term: 'crack spread',
    also: ['refining margin', 'crack'],
    short: 'The gap between what a refinery pays for crude and what it gets for the fuels it makes from it.',
    note: 'A refinery is long the crack whether it likes it or not, which is why refiners hedge by selling it.',
    lessonId: 'the-physical-chain',
    markets: true,
  },
  {
    id: 'basis-risk',
    term: 'basis risk',
    also: ['basis', 'hedge mismatch', 'imperfect hedge'],
    short: 'The risk left over when what you hedged with is not exactly what you own.',
    note: 'Hedge a sour cargo in Nigeria with Brent futures and you have swapped price risk for the risk that the two stop moving together. That gap is where hedged traders still lose money.',
    lessonId: 'hedging-the-physical',
    markets: true,
  },
  {
    id: 'margin-call',
    term: 'margin call',
    also: ['margin', 'variation margin', 'collateral'],
    short: 'A demand for more cash from the exchange when the market moves against your futures position.',
    note: 'The cruelty of hedging physical: the paper leg demands cash today while the barrels it protects pay nothing until they are delivered.',
    lessonId: 'hedging-the-physical',
    markets: true,
  },
  {
    id: 'mark-to-market',
    term: 'mark to market',
    also: ['daily settlement', 'marked'],
    short: 'Settling a futures position\'s gain or loss every day, in cash, rather than at the end.',
    note: 'It is why a perfectly hedged trader can still run out of money: the hedge is settled daily, the cargo is settled once.',
    lessonId: 'hedging-the-physical',
    markets: true,
  },
  // ---------- Markets track: gas and LNG pricing, the paper market, and options. ----------
  {
    id: 'mmbtu',
    term: 'MMBtu',
    also: ['mmbtu', 'million btu', 'btu', 'dollars per mmbtu', 'energy unit'],
    short: 'The unit gas and LNG are priced in: one million British thermal units, which is an amount of energy rather than an amount of volume.',
    note: 'A standard cargo is very roughly 3.4 million of them, so a $1 move in the price is about $3.4 million on that one ship. That is why the market argues over cents.',
    lessonId: 'how-lng-is-priced',
    demo: 'cargo = 3_400_000  # MMBtu in one standard LNG cargo\nprint(f"at $12.50/MMBtu: ${cargo * 12.50 / 1e6:.1f}m")\nprint(f"$1/MMBtu higher: ${cargo * 13.50 / 1e6:.1f}m")\n',
    markets: true,
  },
  {
    id: 'slope',
    term: 'slope',
    also: ['oil-linked', 'oil indexation', 'brent slope', 'percentage of brent'],
    short: 'The percentage of a crude price that an oil-linked LNG contract pays: 14% of $80 Brent is $11.20 per [[mmbtu]].',
    note: 'Long-term Asian LNG contracts still price this way, so the whole contract is one multiplication and the negotiation is entirely about that one number. At a 14% slope, a $10 move in Brent moves the gas price $1.40.',
    lessonId: 'how-lng-is-priced',
    demo: 'brent = 80.00  # $/barrel\nslope = 0.14   # the contract pays 14% of Brent\nprint(f"{brent * slope:.2f} $/MMBtu")\n',
    markets: true,
  },
  {
    id: 'jkm',
    term: 'JKM',
    also: ['jkm', 'japan korea marker', 'asian lng price', 'lng spot'],
    short: 'The spot price marker for LNG delivered into North East Asia — Japan, Korea, China and Taiwan.',
    note: 'What a cargo sold spot is measured against, rather than on a [[slope]]. It is an assessed price, built by a reporting agency out of deals and bids, not an exchange settlement.',
    lessonId: 'how-lng-is-priced',
    markets: true,
  },
  {
    id: 'ttf',
    term: 'TTF',
    also: ['ttf', 'dutch ttf', 'title transfer facility', 'european gas'],
    short: 'The Dutch trading hub whose gas price is Europe\'s benchmark, quoted in euros per megawatt hour.',
    note: 'It decides where a flexible cargo goes: when Europe pays more than [[jkm]] net of [[freight]], ships turn west. The euro-per-MWh quote has to be converted before it can be compared with a dollar-per-[[mmbtu]] price.',
    lessonId: 'how-lng-is-priced',
    markets: true,
  },
  {
    id: 'henry-hub',
    term: 'Henry Hub',
    also: ['henry hub', 'hh', 'us gas price', 'nymex gas'],
    short: 'The American natural gas benchmark, set at a pipeline junction in Louisiana and quoted in dollars per [[mmbtu]].',
    note: 'US LNG is typically sold at 115% of it plus a fixed liquefaction fee, so American supply competes on a completely different formula from an oil-linked [[slope]]. That is the argument between the two pricing worlds.',
    lessonId: 'how-lng-is-priced',
    markets: true,
  },
  {
    id: 'futures-contract',
    term: 'futures contract',
    also: ['futures', 'future', 'exchange traded', 'lots'],
    short: 'A standardised agreement, traded on an exchange and settled in cash every day, to buy or sell a fixed quantity at an agreed price on a set date.',
    note: 'Standard is the point: everyone trades the identical lot, so it is liquid and the exchange stands between you and the other side. The cost is that it is settled daily ([[mark-to-market]]) and it is not your cargo ([[basis-risk]]).',
    lessonId: 'futures-and-swaps',
    markets: true,
  },
  {
    id: 'swap',
    term: 'swap',
    also: ['swaps', 'cfd', 'cash settled', 'average price swap'],
    short: 'A cash settlement of a floating average price against a fixed one, agreed bilaterally or through a clearer, with no cargo changing hands.',
    note: 'A producer\'s revenue is an average over a month, not a price on one afternoon. A monthly-average swap settles against that same average, so it matches the physical where a single-date future leaves a gap.',
    lessonId: 'futures-and-swaps',
    markets: true,
  },
  {
    id: 'strip',
    term: 'strip',
    also: ['strips', 'calendar strip', 'cal-26', 'twelve months'],
    short: 'The run of consecutive monthly contracts you sell in one go to hedge a whole year.',
    note: 'Selling "Cal-26" is selling twelve months at once, and the price quoted is their average. Hedging a year with the front month instead leaves eleven months uncovered and a rolling cost every time it expires.',
    lessonId: 'futures-and-swaps',
    markets: true,
  },
  {
    id: 'tenor',
    term: 'tenor',
    also: ['maturity', 'how far out', 'front month', 'back end'],
    short: 'How far into the future a contract runs, from the front month out to years ahead.',
    note: 'Liquidity thins fast with it. The front few months trade constantly, while a hedge three years out may have to be done bilaterally and at a visibly worse price.',
    lessonId: 'futures-and-swaps',
    markets: true,
  },
  {
    id: 'hedge-ratio',
    term: 'hedge ratio',
    also: ['hedged percentage', 'how much is hedged', 'coverage'],
    short: 'The share of your production you have already sold forward.',
    note: 'Almost nobody sets it at 100%: a full hedge means a rally earns you nothing, and volumes that fail to turn up leave you short paper you have to buy back. Boards argue about this number more than about the price view behind it.',
    lessonId: 'futures-and-swaps',
    markets: true,
  },
  {
    id: 'put',
    term: 'put',
    also: ['puts', 'put option', 'floor', 'downside protection'],
    short: 'The right, but not the obligation, to sell at a fixed price — a producer\'s floor under the market.',
    note: 'You pay a [[premium]] for it up front, and that is the most you can lose. Unlike a future it protects the downside while leaving the rally intact, which is exactly what the premium buys.',
    confusedWith: 'call',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'call',
    term: 'call',
    also: ['calls', 'call option', 'ceiling', 'upside'],
    short: 'The right, but not the obligation, to buy at a fixed price — a consumer\'s ceiling over the market.',
    note: 'A producer is usually on the other side of one: selling it brings in premium now and caps what you receive if prices run. That cap is what pays for a [[zero-cost-collar]].',
    confusedWith: 'put',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'strike',
    term: 'strike',
    also: ['strike price', 'exercise price'],
    short: 'The fixed price written into an option: the level at which the holder may buy or sell.',
    note: 'It is chosen, not given. A floor set further below the market costs less [[premium]], because it is less likely ever to pay out.',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'premium',
    term: 'premium',
    also: ['option premium', 'option cost', 'paid up front'],
    short: 'What an option costs, paid up front to whoever wrote it.',
    note: 'It is a sunk cost, not a deposit: it is gone whether or not the option is ever used. For the buyer it is also the entire loss they can make, which is why an option is easier to take to a board than a future.',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'collar',
    term: 'collar',
    also: ['collars', 'floor and ceiling', 'fence'],
    short: 'A bought [[put]] plus a sold [[call]]: a floor you pay for by giving away the upside above a ceiling.',
    note: 'Between the two strikes you keep the market price; outside them you keep neither the fall nor the rally. It is the commonest producer hedge because it needs far less cash than buying protection outright.',
    demo: 'floor, ceiling = 70.0, 95.0  # bought put at 70, sold call at 95\nfor market in (60.0, 80.0, 110.0):\n    print(f"market ${market:.0f} -> realised ${min(max(market, floor), ceiling):.0f}")\n',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'zero-cost-collar',
    term: 'zero-cost collar',
    also: ['costless collar', 'zero premium collar'],
    short: 'A [[collar]] whose two premiums exactly cancel, so nothing is paid up front.',
    note: '"Zero cost" means no premium, not no cost. The cost is the upside you sold to pay for the floor, and it only becomes visible in the year the market rallies past the ceiling.',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'implied-volatility',
    term: 'implied volatility',
    also: ['vol', 'implied vol', 'iv'],
    short: 'How much movement the options market is pricing in, quoted as an annualised percentage.',
    note: 'It is backed out of option prices rather than measured from history, so it is a forecast someone is willing to trade on. When it rises, every floor gets dearer at the same [[strike]].',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'delta',
    term: 'delta',
    also: ['hedge delta', 'delta hedging'],
    short: 'Roughly how much of the underlying position an option behaves like, as a number between zero and one.',
    note: 'A floor at 0.3 covers about 30% of a barrel today, not all of it, so options and futures of the same headline volume are not the same [[hedge-ratio]]. It also moves as the market moves, which is why delta hedges are re-set.',
    lessonId: 'options-and-collars',
    markets: true,
  },
  {
    id: 'ohlc',
    term: 'OHLC',
    also: ['ohlc', 'open high low close', 'candlestick', 'bar chart'],
    short: 'Open, high, low, close: the four numbers that make up one bar on a price chart.',
    note: 'The close is what positions are settled and margined against; the high and low are where it traded on the way there. A chart of closes alone hides the morning that went 4% against you and came back.',
    lessonId: 'the-screens-traders-read',
    markets: true,
  },
  {
    id: 'seasonality',
    term: 'seasonality',
    also: ['seasonal', 'winter hump', 'summer trough'],
    short: 'The repeating yearly shape in a gas or power curve: the winter hump everyone can see a year ahead.',
    note: 'It is not an edge, because it is already in the forward price. What moves money is the weather coming out different from the shape the whole market had priced in.',
    lessonId: 'the-screens-traders-read',
    markets: true,
  },
];
