// Lightweight index of every question, generated by scripts/verify-content.ts into generated/question-index.json.
import type { Diff, ExamSlot, Format, RuleId, TopicId } from './ids.ts';

export interface QuestionMeta {
  qid: string;
  topicId: TopicId;
  scenarioId: string;
  /** The scenario's title ("Rottnest ferry timetable"), so search need not load the topic chunks. */
  scenarioTitle: string;
  format: Format;
  diff: Diff;
  core: boolean;
  title: string;
  concepts: string[];
  detects: string[];
  expectedSec: number;
  /** write questions only */
  paper?: boolean;
  /** write questions only */
  kind?: 'function' | 'program' | 'project';
  /** write questions only */
  rules?: RuleId[];
  /** paper-mode write questions only: the final-paper slot this question can fill, and its marks */
  examSlot?: ExamSlot;
  marks?: number;
}
