// Lightweight index of every question, generated by scripts/verify-content.ts into generated/question-index.json.
import type { Diff, Format, RuleId, TopicId } from './ids.ts';

export interface QuestionMeta {
  qid: string;
  topicId: TopicId;
  scenarioId: string;
  format: Format;
  diff: Diff;
  core: boolean;
  title: string;
  concepts: string[];
  detects: string[];
  expectedSec: number;
  /** write questions only */
  paper?: boolean;
  /** write questions only */
  kind?: 'function' | 'program' | 'project';
  /** write questions only */
  rules?: RuleId[];
}
