// Exam questions for "What makes a model a GLM: family, link and variance".
//
// Every output shown with a question was printed by R when the verifier ran it, and every number
// question's answer is an R expression the verifier evaluates: no option, prompt or explanation states a
// number R worked out. Definitions (V(mu) = mu^2, g(mu) = 1/mu) and inputs the question chooses are fine.
import type { StatQuestion } from '../../statQuestionSchema.ts';

const questions: StatQuestion[] = [
  {
    id: 'gt-three-parts',
    lessonId: 'glm-theory',
    kind: 'choice',
    marks: 2,
    prompt: 'A GLM has three parts: a distribution for the response, a linear predictor and a link. Which of them does the formula `count ~ spray` set in this model?',
    code: 'fit <- glm(count ~ spray, family = poisson, data = InsectSprays)\nfamily(fit)\n',
    options: [
      { text: 'The linear predictor: which terms get a coefficient', correct: true },
      { text: 'The distribution of the counts' },
      { text: 'The link function' },
      { text: 'The dispersion' },
    ],
    explain: 'The formula lists the terms of η = β₀ + β₁x₁ + …, the only part with coefficients. The distribution and the link come from `family = poisson`, which is what `family(fit)` reports, and the Poisson family fixes the dispersion at 1.',
  },
  {
    id: 'gt-gamma-spread',
    lessonId: 'glm-theory',
    kind: 'choice',
    marks: 2,
    prompt: 'Under this family, with one value of φ for the whole model, two observations have means 2 and 4. How does the standard deviation of the second compare with the first?',
    code: 'fam <- Gamma()\nfam$variance(c(1, 2, 4))\n',
    options: [
      { text: 'It is twice as large', correct: true },
      { text: 'It is four times as large' },
      { text: 'It is the same' },
      { text: 'It is √2 times as large' },
    ],
    explain: 'The output shows the Gamma variance function is V(μ) = μ², so Var(Y) = φ μ² and the standard deviation is √φ · μ, proportional to the mean. Doubling the mean doubles the standard deviation and multiplies the variance by four. The same spread for every mean is the Gaussian family, and √2 times would be the Poisson rule V(μ) = μ.',
  },
  {
    id: 'gt-binomial-variance',
    lessonId: 'glm-theory',
    kind: 'predict',
    marks: 2,
    prompt: 'The binomial variance function is V(μ) = μ(1 − μ). What does this print?',
    code: 'fam <- binomial()\nfam$variance(c(0.2, 0.5))\n',
    choices: [
      '[1] 0.16 0.25',
      '[1] 0.2 0.5',
      '[1] 0.04 0.25',
      '[1] 1 1',
    ],
    explain: '`$variance` is V itself, so it returns μ(1 − μ) at each mean. Returning the means unchanged would be the Poisson variance function, squaring them the Gamma one, and a constant 1 the Gaussian one.',
  },
  {
    id: 'gt-gaussian-dispersion',
    lessonId: 'glm-theory',
    kind: 'number',
    marks: 3,
    prompt: 'The same model is refitted as `glm(dist ~ speed, family = gaussian, data = cars)`. What dispersion will `summary()` of that fit report? Give it to one decimal place.',
    code: 'fit <- lm(dist ~ speed, data = cars)\nsummary(fit)$sigma\n',
    answer: 'round(summary(fit)$sigma^2, 1)',
    tol: 0.06,
    unit: 'square feet',
    explain: 'The Gaussian GLM with the identity link is the linear model, and its dispersion φ is σ², the residual variance. `summary(fit)$sigma` is the residual standard error, σ, so square it.',
  },
  {
    id: 'gt-linkinv-prob',
    lessonId: 'glm-theory',
    kind: 'number',
    marks: 3,
    prompt: 'This is the linear predictor for a car weighing 3 thousand pounds. What probability of a manual gearbox does the model give it? Give it to three decimal places.',
    code: 'fit <- glm(am ~ wt, family = binomial, data = mtcars)\npredict(fit, data.frame(wt = 3))\n',
    answer: 'round(plogis(predict(fit, data.frame(wt = 3))), 3)',
    tol: 0.0006,
    explain: '`predict()` answers on the link scale, here the log-odds. The inverse of the logit link is μ = exp(η) / (1 + exp(η)), which is `plogis()` in R and also `family(fit)$linkinv`; `predict(fit, data.frame(wt = 3), type = "response")` does the same in one step.',
  },
  {
    id: 'gt-lm-glm',
    lessonId: 'glm-theory',
    kind: 'choice',
    marks: 2,
    prompt: 'Why do these two fits give the same coefficients?',
    code: 'coef(lm(dist ~ speed, data = cars))\ncoef(glm(dist ~ speed, family = gaussian, data = cars))\n',
    options: [
      { text: 'The linear model is the GLM with the normal family and the identity link, and for it iteratively reweighted least squares is ordinary least squares', correct: true },
      { text: 'glm() hands any model with a numeric response over to lm()' },
      { text: 'They agree only because speed has no missing values' },
      { text: 'glm() ignores the family argument unless a link is named' },
    ],
    explain: 'With the identity link the working response is y itself, and with V(μ) = 1 every weight is 1, so the weighted least squares fit in each round is the ordinary least squares line. `glm()` runs its usual algorithm; it does not call `lm()`, and it uses the family whether or not a link is named.',
  },
  {
    id: 'gt-quasi',
    lessonId: 'glm-theory',
    kind: 'choice',
    marks: 2,
    prompt: 'What does the quasi-Poisson family specify?',
    code: 'fam <- quasipoisson()\nfam$link\nfam$variance(c(1, 5))\nfam$dispersion\n',
    options: [
      { text: 'A log link and a variance proportional to the mean, with φ left to be estimated, and no distribution for the counts', correct: true },
      { text: 'A Poisson distribution with φ fixed at 1' },
      { text: 'A negative binomial distribution with an extra parameter for the spread' },
      { text: 'A variance that grows with the square of the mean' },
    ],
    explain: 'The output shows a log link, a variance function equal to the mean, and a dispersion of `NA`: not fixed, so estimated from the data. A quasi family names only a link and a variance function, which is why it has no likelihood and no AIC. The Poisson family fixes φ at 1, a negative binomial is a real distribution fitted with `glm.nb()`, and V(μ) = μ² is the Gamma variance function.',
  },
  {
    id: 'gt-canonical-range',
    lessonId: 'glm-theory',
    kind: 'choice',
    marks: 2,
    prompt: 'R uses each family\'s canonical link as its default. Which of these default links does **not** guarantee that a fitted mean lies in the range its response can take?',
    options: [
      { text: 'The Gamma family\'s inverse link, 1/μ: a negative linear predictor gives a negative mean, though a Gamma response is always positive', correct: true },
      { text: 'The Poisson family\'s log link' },
      { text: 'The binomial family\'s logit link' },
      { text: 'None of them: every canonical link keeps the mean in range' },
    ],
    explain: 'The inverse of the log link is exp(η), which is positive for any η, and the inverse of the logit is always between 0 and 1. The inverse link gives μ = 1/η, which is negative whenever η is, so nothing stops a Gamma fit with its default link from predicting a negative mean. That is one reason the log link is often chosen for Gamma models instead.',
  },
  {
    id: 'gt-not-converged',
    lessonId: 'glm-theory',
    kind: 'choice',
    marks: 2,
    prompt: 'Someone fits this model and gets this output. What should they do next?',
    code: 'fit <- glm(am ~ wt, family = binomial, data = mtcars, control = glm.control(maxit = 3))\nfit$converged\n',
    options: [
      { text: 'Refit allowing more rounds, with a larger maxit, and check that converged is TRUE before using the estimates', correct: true },
      { text: 'Report the coefficients as they are; the warning only affects the p-values' },
      { text: 'Switch to lm(), which never needs more than one round' },
      { text: 'Nothing: converged is FALSE because the model already fits the data perfectly' },
    ],
    explain: '`glm()` stopped because it ran out of rounds (`maxit = 3`), not because the deviance had settled, so the estimates are not yet the maximum likelihood estimates. With the default `maxit`, or a larger one, the fit runs until the change in the deviance is below `epsilon`. `lm()` would fit a different model, and a perfect fit is a separate problem with its own warning.',
  },
  {
    id: 'gt-write-link',
    lessonId: 'glm-theory',
    kind: 'write',
    marks: 5,
    prompt: 'Write a function `to_link(fit, mu)` that takes a fitted `glm()` and some means on its response scale, and returns them on the link scale. Use the fit\'s own link function, `family(fit)$linkfun`, so the same function works for any family.',
    run: 'function',
    fnName: 'to_link',
    starter: 'to_link <- function(fit, mu) {\n  # find the fit\'s link function and apply it to mu\n}\n',
    solution: 'to_link <- function(fit, mu) {\n  family(fit)$linkfun(mu)\n}\n',
    tests: [
      { id: 'poisson', label: 'a Poisson fit: the log link', hidden: false, setup: 'fit <- glm(count ~ spray, family = poisson, data = InsectSprays)', call: 'to_link(fit, c(1, 2, 10))', expect: 'log(c(1, 2, 10))', cmp: 'float' },
      { id: 'binomial', label: 'a binomial fit: the logit link', hidden: false, setup: 'fit <- glm(am ~ wt, family = binomial, data = mtcars)', call: 'to_link(fit, c(0.2, 0.5, 0.9))', expect: 'qlogis(c(0.2, 0.5, 0.9))', cmp: 'float' },
      { id: 'gamma', label: 'a Gamma fit with its default inverse link', hidden: true, setup: 'fit <- glm(mpg ~ wt, family = Gamma, data = mtcars)', call: 'to_link(fit, c(20, 25))', expect: '1 / c(20, 25)', cmp: 'float' },
      { id: 'predictions', label: 'agrees with predict() on the link scale', hidden: true, setup: 'fit <- glm(am ~ wt, family = binomial, data = mtcars)', call: 'to_link(fit, predict(fit, data.frame(wt = c(2, 3, 4)), type = "response"))', expect: 'local({ f <- glm(am ~ wt, family = binomial, data = mtcars); predict(f, data.frame(wt = c(2, 3, 4))) })', cmp: 'float' },
    ],
    explain: '`family(fit)` is the family object the model was fitted with, and `$linkfun` is its link g, so `family(fit)$linkfun(mu)` computes g(μ) = η for whichever family it is. Writing `log(mu)` passes the Poisson test and fails the others; the fit\'s own link is right for all of them.',
  },
];

export default questions;
