// Exam questions for "Yes or no: logistic regression".
//
// Every output shown with a question was printed by R when the verifier ran it, and every number
// question's answer is an R expression the verifier evaluates: no option, prompt or explanation states a
// number R worked out. Datasets vary from the lesson's own mtcars/am example where they can (mtcars/vs,
// mtcars/hp, infert) so a question tests the idea rather than a memorised output.
import type { StatQuestion } from '../../statQuestionSchema.ts';

const questions: StatQuestion[] = [
  {
    id: 'lr-lm-range',
    lessonId: 'logistic-regression',
    kind: 'choice',
    marks: 2,
    prompt: 'The response is 1 for a straight engine (`vs`) and 0 for a V-shaped one. What does this range tell you about fitting `vs` with `lm()`?',
    code: 'fit <- lm(vs ~ wt, data = mtcars)\nrange(fitted(fit))\n',
    options: [
      { text: 'At least one fitted value is not a valid probability, since it falls outside 0 to 1', correct: true },
      { text: 'The model fits well, since fitted values close to 0 and 1 mean confident predictions' },
      { text: 'wt is not related to vs, since the fitted values are spread over a wide range' },
      { text: 'R would have refused to fit this if wt were a poor predictor' },
    ],
    explain: 'A straight line has no idea its output is meant to be a probability, so nothing stops it landing below 0 or above 1 for cars in the data. Fitted values do not indicate a good or bad fit by themselves, and R fits whatever formula it is given whether or not the model suits the data.',
  },
  {
    id: 'lr-odds-def',
    lessonId: 'logistic-regression',
    kind: 'number',
    marks: 2,
    prompt: 'The odds of an event are p / (1 - p). Using the probability shown above, what are the odds? Give your answer to two decimal places.',
    code: 'p <- 0.35\np\n',
    answer: 'p / (1 - p)',
    tol: 0.006,
    explain: 'Odds are the chance something happens divided by the chance it does not: p / (1 - p).',
  },
  {
    id: 'lr-predicted-prob',
    lessonId: 'logistic-regression',
    kind: 'number',
    marks: 3,
    prompt: 'Using the coefficients above, what probability of being a case does the model predict for someone aged 30? First get the log-odds (intercept + slope x age), then convert with `plogis()`. Give your answer to two decimal places.',
    code: 'fit <- glm(case ~ age, family = binomial, data = infert)\ncoef(fit)\n',
    answer: 'round(predict(fit, data.frame(age = 30), type = "response"), 2)',
    tol: 0.006,
    unit: 'probability',
    explain: 'The linear predictor is the intercept plus the slope times 30; `plogis()` of that is the probability. `predict(fit, newdata, type = "response")` does the same sum in one step.',
  },
  {
    id: 'lr-predict-format',
    lessonId: 'logistic-regression',
    kind: 'predict',
    marks: 2,
    prompt: 'What does this print?',
    code: 'fit <- glm(vs ~ wt, family = binomial, data = mtcars)\nnew <- data.frame(wt = c(2, 4))\nround(predict(fit, new, type = "response"), 3)\n',
    choices: [
      '    1     2 \n0.869 0.127 ',
      '     1      2 \n 1.894 -1.928 ',
      '    1     2 \n0.127 0.869 ',
      '[1] 0.869 0.127',
    ],
    explain: '`type = "response"` gives a probability for each row of `new`, named by row number. Leaving `type` out would give the log-odds instead, and a plain `[1]` vector has no names at all.',
  },
  {
    id: 'lr-oddsratio-small-step',
    lessonId: 'logistic-regression',
    kind: 'choice',
    marks: 3,
    prompt: 'The `hp` value above is below 1, but only a little. What is the right way to read it?',
    code: 'fit <- glm(vs ~ hp, family = binomial, data = mtcars)\nexp(coef(fit))\n',
    options: [
      { text: 'Each extra unit of horsepower multiplies the odds of a straight engine by that factor; it looks close to 1 because one extra horsepower is a tiny step, but the effect over 50 or 100 horsepower compounds', correct: true },
      { text: 'Each extra unit of horsepower subtracts that amount from the probability of a straight engine' },
      { text: 'Each extra unit of horsepower multiplies the probability of a straight engine by that factor' },
      { text: 'Since the ratio is close to 1, horsepower has essentially no effect on the engine shape' },
    ],
    explain: 'An odds ratio near 1 for a one-unit step does not mean the predictor is unimportant: it means the step is small relative to how much hp varies. Multiplying it out over a bigger step of horsepower shows the real size of the effect. The multiplier applies to the odds, never directly to the probability.',
  },
  {
    id: 'lr-confint-scale',
    lessonId: 'logistic-regression',
    kind: 'choice',
    marks: 3,
    prompt: 'What does the interval in the `wt` row represent?',
    code: 'fit <- glm(vs ~ wt, family = binomial, data = mtcars)\nexp(confint(fit))\n',
    options: [
      { text: 'A 95% confidence interval for the odds ratio per extra unit of wt (a thousand pounds)', correct: true },
      { text: 'A 95% confidence interval for the probability of a straight engine' },
      { text: 'A 95% confidence interval for the log-odds slope, before exponentiating' },
      { text: 'The range of weights observed among the 32 cars' },
    ],
    explain: '`confint(fit)` gives an interval for the coefficient on the log-odds scale; exponentiating it turns both ends into odds ratios, exactly the way exponentiating the estimate itself does.',
  },
  {
    id: 'lr-z-not-t',
    lessonId: 'logistic-regression',
    kind: 'choice',
    marks: 2,
    prompt: 'Why does this summary use a `z value` column rather than the `t value` an `lm()` summary shows?',
    code: 'fit <- glm(case ~ age + parity + induced + spontaneous, family = binomial, data = infert)\nsummary(fit)\n',
    options: [
      { text: 'The binomial family fixes the variance once the mean (the probability) is known, so there is no separate residual variance to estimate, and the test uses the normal distribution instead of the t distribution', correct: true },
      { text: 'z values are used because some of the predictors are counts rather than measurements' },
      { text: 'With more than two predictors, R switches automatically from t to z' },
      { text: 'It is just glm()\'s naming convention for the same t-test' },
    ],
    explain: 'A linear model estimates its own error variance from the residuals, which is why it uses a t distribution with residual degrees of freedom. A binomial glm has no such spare parameter to estimate, so its coefficients are judged against the normal (z) distribution instead.',
  },
  {
    id: 'lr-deviance-drop',
    lessonId: 'logistic-regression',
    kind: 'choice',
    marks: 2,
    prompt: 'The residual deviance here is noticeably lower than the null deviance. What does that tell you?',
    code: 'fit <- glm(case ~ age + parity + induced + spontaneous, family = binomial, data = infert)\nsummary(fit)\n',
    options: [
      { text: 'Together, the four predictors explain some of why some women are cases and others are not, compared with a model that ignores them entirely', correct: true },
      { text: 'The model accounts for that percentage of the variation, the same way R-squared would for a linear model' },
      { text: 'Every one of the four predictors individually has a real effect' },
      { text: 'The model must be wrong, since a well-fitting model should have almost no deviance at all' },
    ],
    explain: 'Deviance measures distance from a perfect fit; the drop from the null model (only an intercept) to this one is what the predictors bought together. A glm has no R-squared, the drop says nothing about any one predictor on its own, and some residual deviance is expected even from a good model.',
  },
  {
    id: 'lr-class-predict',
    lessonId: 'logistic-regression',
    kind: 'predict',
    marks: 2,
    prompt: 'What does this print?',
    code: 'fit <- glm(vs ~ hp, family = binomial, data = mtcars)\nclass(fit)\n',
    choices: ['[1] "glm" "lm"', '[1] "glm"', '[1] "lm" "glm"', '[1] "binomial"'],
    explain: 'A fitted glm object carries both classes, `"glm"` first: many functions written for `lm` objects still work on it, because R looks for a `glm` method first and falls back to the `lm` one.',
  },
  {
    id: 'lr-predicted-prob-fn',
    lessonId: 'logistic-regression',
    kind: 'write',
    marks: 5,
    prompt: 'Write a function `predicted_prob(fit, newdata)` that takes a fitted logistic regression and a data frame of new rows, and returns the predicted probabilities as plain numbers (no names).',
    run: 'function',
    fnName: 'predicted_prob',
    starter: 'predicted_prob <- function(fit, newdata) {\n  # use predict() with the right type to get a probability\n}\n',
    solution: 'predicted_prob <- function(fit, newdata) {\n  unname(predict(fit, newdata, type = "response"))\n}\n',
    tests: [
      {
        id: 'vs-wt', label: 'engine shape from weight, one car', hidden: false,
        setup: 'fit <- glm(vs ~ wt, family = binomial, data = mtcars)',
        call: 'predicted_prob(fit, data.frame(wt = 3))',
        expect: 'unname(predict(glm(vs ~ wt, family = binomial, data = mtcars), data.frame(wt = 3), type = "response"))',
        cmp: 'float',
      },
      {
        id: 'infert-age', label: 'case status from age, one woman', hidden: false,
        setup: 'fit <- glm(case ~ age, family = binomial, data = infert)',
        call: 'predicted_prob(fit, data.frame(age = 28))',
        expect: 'unname(predict(glm(case ~ age, family = binomial, data = infert), data.frame(age = 28), type = "response"))',
        cmp: 'float',
      },
      {
        id: 'several', label: 'several weights at once', hidden: true,
        setup: 'fit <- glm(vs ~ wt, family = binomial, data = mtcars)',
        call: 'predicted_prob(fit, data.frame(wt = c(2, 3, 4)))',
        expect: 'unname(predict(glm(vs ~ wt, family = binomial, data = mtcars), data.frame(wt = c(2, 3, 4)), type = "response"))',
        cmp: 'float',
      },
      {
        id: 'different-model', label: 'a different predictor, hp', hidden: true,
        setup: 'fit <- glm(vs ~ hp, family = binomial, data = mtcars)',
        call: 'predicted_prob(fit, data.frame(hp = c(100, 200)))',
        expect: 'unname(predict(glm(vs ~ hp, family = binomial, data = mtcars), data.frame(hp = c(100, 200)), type = "response"))',
        cmp: 'float',
      },
    ],
    explain: '`predict()` needs `type = "response"` to return a probability rather than a log-odds; `unname()` drops the row names, though the tests accept either since they compare with tolerance.',
  },
];

export default questions;
