// Exam questions for "R for this unit: vectors, data frames and factors".
//
// Every output shown with a question was printed by R when the verifier ran it, and every number
// question's answer is an R expression the verifier evaluates: no option, prompt or explanation states a
// number R worked out.
import type { StatQuestion } from '../../statQuestionSchema.ts';

const questions: StatQuestion[] = [
  {
    id: 'rb-minus-index',
    lessonId: 'r-basics',
    kind: 'predict',
    marks: 2,
    prompt: 'What does this print?',
    code: 'x <- c(10, 20, 30, 40, 50)\nx[-2]\n',
    choices: [
      '[1] 10 30 40 50',
      '[1] 40',
      '[1] 10 20 30 50',
      '[1] 20',
    ],
    explain: 'A minus sign inside the brackets leaves that position out, so `x[-2]` is every value except the second. It does not count from the end, as it would in Python, and R counts positions from 1, not 0.',
  },
  {
    id: 'rb-levels-order',
    lessonId: 'r-basics',
    kind: 'predict',
    marks: 2,
    prompt: 'What does this print?',
    code: 'sizes <- factor(c("small", "large", "medium", "small"))\nlevels(sizes)\n',
    choices: [
      '[1] "large"  "medium" "small" ',
      '[1] "small"  "large"  "medium"',
      '[1] "small"  "medium" "large" ',
      '[1] "small"  "large"  "medium" "small" ',
    ],
    explain: 'Given no `levels =`, `factor()` puts the levels in alphabetical order, not the order they first appear in and not the order that makes sense to a person. Each level is listed once, however many times it occurs. To choose the order, write `factor(x, levels = c("small", "medium", "large"))`.',
  },
  {
    id: 'rb-str-columns',
    lessonId: 'r-basics',
    kind: 'choice',
    marks: 2,
    prompt: 'Which statement about the columns of `iris` is right?',
    code: 'str(iris)\n',
    options: [
      { text: '`Species` is a factor, and the other columns are numeric', correct: true },
      { text: 'Every column is numeric, since `str()` shows numbers after each of them' },
      { text: '`Species` is plain text, since its levels are words' },
      { text: 'None of the columns is a factor, since a factor would show its values as words' },
    ],
    explain: '`str()` names each column\'s type first: `num` for numbers and `Factor` for a factor, followed by its levels. The numbers after a factor are codes: the position of each value\'s level in the list of levels, not measurements. Plain text would show as `chr`, with its values in quotes.',
  },
  {
    id: 'rb-rows-and-columns',
    lessonId: 'r-basics',
    kind: 'choice',
    marks: 2,
    prompt: 'What has this line picked out of `mtcars`?',
    code: 'mtcars[mtcars$mpg > 30, c("mpg", "wt")]\n',
    options: [
      { text: 'The `mpg` and `wt` columns, for the cars whose `mpg` is above 30', correct: true },
      { text: 'The first 30 rows of the `mpg` and `wt` columns' },
      { text: 'Every column, for the cars whose `mpg` and `wt` are both above 30' },
      { text: 'The cars whose `mpg` is above 30, sorted by `mpg` and then by `wt`' },
    ],
    explain: 'In `df[rows, columns]`, the part before the comma chooses rows and the part after chooses columns. `mtcars$mpg > 30` is `TRUE` or `FALSE` for each car, so it keeps the rows where it is `TRUE`; `c("mpg", "wt")` names the columns to keep. Nothing is sorted, and the condition is only on `mpg`.',
  },
  {
    id: 'rb-relevel-baseline',
    lessonId: 'r-basics',
    kind: 'choice',
    marks: 2,
    prompt: 'A model of `breaks ~ tension` is fitted to `wb` next. Which tension will the other two be compared with?',
    code: 'wb <- warpbreaks\nlevels(wb$tension)\nwb$tension <- relevel(wb$tension, ref = "H")\nlevels(wb$tension)\n',
    options: [
      { text: '`H`, the level `relevel()` moved to the front', correct: true },
      { text: 'The level that was first before `relevel()` was called' },
      { text: '`M`, because it is the middle setting' },
      { text: 'None of them: each tension is compared with the average of all three' },
    ],
    explain: 'A model compares each level of a factor with the baseline, which is the first level. `relevel(ref = "H")` moved `H` to the front, as the second `levels()` line shows, and left the data itself unchanged. The level that used to be first is now one of the two compared with `H`, and no level is compared with an overall average.',
  },
  {
    id: 'rb-na-mean',
    lessonId: 'r-basics',
    kind: 'choice',
    marks: 2,
    prompt: 'Why do these two lines give different answers?',
    code: 'mean(airquality$Ozone)\nmean(airquality$Ozone, na.rm = TRUE)\n',
    options: [
      { text: 'Some days have no ozone reading; an average that includes an unknown value is unknown, and `na.rm = TRUE` leaves those days out first', correct: true },
      { text: '`na.rm = TRUE` replaces each missing reading with zero before averaging' },
      { text: '`na.rm = TRUE` rounds the answer' },
      { text: 'The first line averages every column of `airquality`, not only `Ozone`' },
    ],
    explain: 'R marks a missing value `NA`, and any mean with an `NA` in it is `NA`, because the answer depends on a value nobody knows. `na.rm = TRUE` removes the `NA`s and averages the rest. Replacing them with zero would pull the average down, and would be a claim about the missing days that the data does not make.',
  },
  {
    id: 'rb-missing-ozone',
    lessonId: 'r-basics',
    kind: 'number',
    marks: 2,
    prompt: 'From the output, how many days in `airquality` have no ozone reading?',
    code: 'summary(airquality$Ozone)\n',
    answer: 'sum(is.na(airquality$Ozone))',
    tol: 0.5,
    unit: 'days',
    explain: 'When a numeric vector has gaps, `summary()` adds a column at the end that counts them. `sum(is.na(airquality$Ozone))` gives the same count, because `is.na()` is `TRUE` for each gap and `TRUE` counts as 1.',
  },
  {
    id: 'rb-manual-share',
    lessonId: 'r-basics',
    kind: 'number',
    marks: 3,
    prompt: 'In `mtcars`, `am` is 1 for a manual gearbox and 0 for an automatic. What percentage of the cars have a manual gearbox? Give a whole number.',
    code: 'table(mtcars$am)\nnrow(mtcars)\n',
    answer: 'round(100 * mean(mtcars$am == 1))',
    tol: 0.6,
    unit: '%',
    explain: '`table()` counts the cars with each value of `am`. Divide the count under `1` by the number of cars and multiply by 100. `mean(mtcars$am == 1)` does the division in one step, because the mean of a `TRUE`/`FALSE` vector is the share that is `TRUE`.',
  },
  {
    id: 'rb-tension-gap',
    lessonId: 'r-basics',
    kind: 'number',
    marks: 3,
    prompt: 'On average, how many more breaks does a length of yarn get at low tension (`L`) than at high tension (`H`)? Give it to two decimal places.',
    code: 'tapply(warpbreaks$breaks, warpbreaks$tension, mean)\n',
    answer: 'round(mean(warpbreaks$breaks[warpbreaks$tension == "L"]) - mean(warpbreaks$breaks[warpbreaks$tension == "H"]), 2)',
    tol: 0.006,
    unit: 'breaks',
    explain: '`tapply()` split the breaks by tension and took the mean of each group, in the order of the levels. Take the `H` mean away from the `L` mean. This difference is exactly what a model with `L` as the baseline would report for `H`, with the sign turned round.',
  },
  {
    id: 'rb-write-group-means',
    lessonId: 'r-basics',
    kind: 'write',
    marks: 5,
    prompt: 'Write a function `group_means(values, groups)` that returns the mean of `values` within each group of `groups`, leaving out missing values: one number per group, in the order of the groups\' levels.',
    run: 'function',
    fnName: 'group_means',
    starter: 'group_means <- function(values, groups) {\n  # one mean per group, leaving out the NAs\n}\n',
    solution: 'group_means <- function(values, groups) {\n  tapply(values, groups, mean, na.rm = TRUE)\n}\n',
    tests: [
      { id: 'small', label: 'two groups built by hand', hidden: false, call: 'group_means(c(1, 2, 3, 10), c("a", "a", "b", "b"))', expect: 'c(a = 1.5, b = 6.5)', cmp: 'float' },
      { id: 'tension', label: 'breaks by tension', hidden: false, call: 'group_means(warpbreaks$breaks, warpbreaks$tension)', expect: 'sapply(split(warpbreaks$breaks, warpbreaks$tension), mean)', cmp: 'float' },
      { id: 'ozone', label: 'ozone by month, with missing readings', hidden: true, call: 'group_means(airquality$Ozone, airquality$Month)', expect: 'sapply(split(airquality$Ozone, airquality$Month), mean, na.rm = TRUE)', cmp: 'float' },
    ],
    explain: '`tapply(values, groups, mean)` splits `values` by `groups` and takes the mean of each piece. Anything after the function is handed on to it, so `na.rm = TRUE` reaches `mean()`; without it, any month with a missing reading has a mean of `NA`.',
  },
];

export default questions;
