// Cheat sheet, worked example and common mistakes for topic 06 (lists, tuples and sorting).
import type { Md, Topic } from '../../schema.ts';

const md = (...lines: string[]): Md => lines.join('\n');

export const cheatsheet: Md = md(
  '**Lists: make, read, change**',
  '',
  'A list is an ordered, changeable sequence. Positions start at 0; negative positions count from the end.',
  '',
  '```python',
  "stops = ['Perth', 'Leederville', 'Glendalough']",
  "stops[0]          # 'Perth'",
  "stops[-1]         # 'Glendalough'",
  "stops[1:3]        # ['Leederville', 'Glendalough']  (stop not included)",
  'len(stops)        # 3',
  "'Perth' in stops  # True",
  "stops[1] = 'City West'   # lists can be changed in place",
  '```',
  '',
  '- `stops[len(stops)]` is an IndexError. The last valid index is `len(stops) - 1`, or just use `stops[-1]`.',
  '- An empty list has no `[0]`. Check `if len(nums) == 0:` before you read the first item.',
  '',
  '**Methods that change the list itself**',
  '',
  '- `nums.append(x)` adds x to the end.',
  '- `nums.insert(i, x)` puts x at position i and shifts the rest right.',
  '- `nums.pop()` removes and returns the last item; `nums.pop(0)` removes and returns the first.',
  '- `nums.remove(x)` removes the first item equal to x (ValueError if there is none).',
  '- `nums.sort()` and `nums.reverse()` reorder the list itself.',
  '- `nums.extend(other)` adds every item of other to the end.',
  '',
  'All of these except `pop` return `None`, so never save their result: `nums = nums.sort()` sets `nums` to `None`. `pop` is the one that hands back a useful value, the item it removed.',
  '',
  '**Things that give you a new value and leave the list alone**',
  '',
  '```python',
  'ordered = sorted(nums)            # new sorted list; nums unchanged',
  'copy = nums[:]                    # or list(nums)',
  'longer = nums + [99]              # new list',
  'low, high = min(nums), max(nums)',
  'total = sum(nums)',
  '```',
  '',
  '**sort() versus sorted()**',
  '',
  '```python',
  'marks = [72, 58, 91]',
  'ranked = sorted(marks, reverse=True)   # ranked is [91, 72, 58], marks unchanged',
  'marks.sort()                           # marks is now [58, 72, 91]; returns None',
  '```',
  '',
  'Inside a function, prefer `sorted(...)` so you do not reorder the caller\'s list.',
  '',
  '**Sorting with key, and breaking ties**',
  '',
  'The key is a function that turns each item into the value to sort by. When the key returns a tuple, Python compares the first parts, then the second parts for ties. Put a minus sign on a number to sort it high to low while text stays A to Z.',
  '',
  '```python',
  "scores = [('Tran', 88), ('Abbott', 88), ('Moss', 95)]",
  '',
  'def points_then_name(entry):',
  '    return (-entry[1], entry[0])',
  '',
  'sorted(scores, key=points_then_name)',
  "# [('Moss', 95), ('Abbott', 88), ('Tran', 88)]",
  '',
  'sorted(scores, key=lambda entry: (-entry[1], entry[0]))   # same, as a lambda',
  "sorted(words, key=len)                                    # shortest word first",
  '```',
  '',
  '- `key=lambda e: e[1], reverse=True` sorts by points only. Tied players keep whatever order they arrived in, which hidden tests usually catch.',
  '- `reverse=True` with the key `(e[1], e[0])` reverses the names too (Z to A). Use the minus sign instead.',
  '- Pass the function name without brackets: `key=points_then_name`, not `key=points_then_name()`.',
  '',
  '**Tuples**',
  '',
  'A tuple is an ordered sequence that cannot be changed. Use it for a fixed group of values, like a `(name, mark)` pair or several values returned at once.',
  '',
  '```python',
  "reading = ('Perth Airport', 38.4)",
  'reading[1]                # 38.4  (indexing and slicing work)',
  "station, temp = reading   # unpacking: one name per item",
  'single = (5,)             # a one-item tuple needs the comma',
  "reading = (reading[0], 39.0)   # fine: builds a new tuple",
  '# reading[1] = 39.0       # TypeError: tuple does not support item assignment',
  '```',
  '',
  '**Returning more than one value**',
  '',
  '```python',
  'def lowest_highest(nums):',
  '    if len(nums) == 0:',
  '        return None',
  '    return (min(nums), max(nums))   # a tuple, exactly as a spec usually asks',
  '',
  'low, high = lowest_highest([4, 9, 2])',
  '```',
  '',
  'If the task says "return a tuple", `[low, high]` is marked wrong even though it prints similarly.',
  '',
  '**Looping over lists of tuples**',
  '',
  '```python',
  "results = [('Singh', 74), ('Lee', 49)]",
  'for name, mark in results:        # unpack each tuple',
  '    if mark >= 50:',
  "        print(name, 'passed')",
  '```',
  '',
  'Use `for i in range(len(nums)):` only when you need the position itself, for example to compare `nums[i]` with `nums[i + 1]` (then stop at `len(nums) - 1`).',
  '',
  '**Aliasing: = does not copy**',
  '',
  '```python',
  "a = ['x', 'y']",
  'b = a          # b and a are the SAME list',
  'c = a[:]       # c is a separate copy',
  "b.append('z')  # a is now ['x', 'y', 'z']; c is still ['x', 'y']",
  '```',
  '',
  '- A list passed to a function is the caller\'s list, not a copy. `append`, `sort`, `remove` or `nums[i] = ...` inside the function change the caller\'s data.',
  '- `nums = nums + [x]` inside a function makes a new list and leaves the caller\'s list alone; `nums += [x]` changes it in place.',
  '',
  '**Lists of lists (grids)**',
  '',
  '```python',
  'grid = [[3, 1, 4],',
  '        [1, 5, 9]]',
  'grid[1][2]          # row 1, column 2: 9',
  'len(grid)           # 2 rows',
  'len(grid[0])        # 3 columns',
  'for row in grid:',
  '    for value in row:',
  '        print(value)',
  '```',
  '',
  '- Build a grid with a loop that appends a new row each time. `[[0] * 3] * 2` repeats the SAME inner list twice, so changing one row changes both.',
  '- `grid[:]` copies the outer list only; the rows inside are still shared.',
  '',
  '**Removing items while looping**',
  '',
  'Removing from the list you are looping over makes the loop skip the item after each removal. Build a new list of the items to keep instead.',
  '',
  '```python',
  'kept = []',
  'for n in nums:',
  '    if n >= 0:',
  '        kept.append(n)',
  '```',
  '',
  '**Exam checklist for list questions**',
  '',
  '1. Empty list: what should the function return, and does anything read `nums[0]` first?',
  '2. Return type: list or tuple, and in what order?',
  '3. Ties: does the spec give a second sort rule?',
  '4. Must the input stay unchanged? Use `sorted()` or a new list.',
  '5. First and last items: does the loop reach both without going past the end?',
);

export const workedExample: Topic['workedExample'] = {
  title: 'Kings Park walk planner: short trails, shortest first',
  code: `def km_then_name(trail):
    return (trail[1], trail[0])


def short_trails(trails, max_km):
    """Return the names of trails no longer than max_km, shortest first, ties A to Z."""
    suitable = []
    for trail in trails:
        if trail[1] <= max_km:
            suitable.append(trail)
    suitable.sort(key=km_then_name)
    names = []
    for name, km in suitable:
        names.append(name)
    return names


trails = [('Law Walk', 2.5), ('Honour Avenues', 1.2), ('Federation Walkway', 2.5), ('Bushland Trail', 3.0)]
print(short_trails(trails, 2.5))
print(trails[0])`,
  steps: [
    '**Pin down the input and the output.** The input is a list of `(name, km)` tuples and a number. The output is a *list of names* (strings), not tuples, ordered by length and then A to Z. Writing one example by hand helps: with `max_km` 2.5 the answer is `[\'Honour Avenues\', \'Federation Walkway\', \'Law Walk\']`.',
    '**Collect the matching items into a new list.** Start `suitable = []` before the loop and `append` each trail whose `trail[1] <= max_km`. Building a new list means the caller\'s `trails` is never changed, and nothing is removed while looping.',
    '**Sort by the rule, with the tie-break in the key.** `km_then_name` turns each trail into `(km, name)`. Tuples compare part by part, so shorter trails come first and trails of equal length fall back to their names. Sorting `suitable` in place is safe because it is our own list. (`key=lambda trail: (trail[1], trail[0])` does the same job.)',
    '**Turn the sorted tuples into the output shape.** Loop with `for name, km in suitable:` to unpack each tuple and append only the name.',
    '**Check the edge cases before you submit.** An empty `trails` or a `max_km` smaller than every trail gives `[]` without any special code. Ties are handled by the key. The last line prints `(\'Law Walk\', 2.5)`, proving the original list kept its order.',
  ],
};

export const commonMistakes: Topic['commonMistakes'] = [
  {
    mistake: 'none_from_inplace',
    bad: 'marks = [72, 58, 91]\nmarks = marks.sort()\nprint(marks[0])',
    good: 'marks = [72, 58, 91]\nmarks.sort()\nprint(marks[0])\n\nranked = sorted(marks)   # when you want a new list',
    note: '`sort()`, `append()`, `insert()`, `remove()` and `reverse()` change the list and return `None`. Call them on their own line, or use `sorted()` to get a new list back.',
  },
  {
    mistake: 'aliasing_copy',
    bad: "backup = seats\nseats.append('A3')   # backup changes too",
    good: "backup = seats[:]    # or list(seats)\nseats.append('A3')   # backup is unchanged",
    note: '`b = a` gives one list two names. Slice with `[:]` or call `list()` when you need a separate copy.',
  },
  {
    mistake: 'mutate_while_iterating',
    bad: 'for n in nums:\n    if n < 50:\n        nums.remove(n)',
    good: 'kept = []\nfor n in nums:\n    if n >= 50:\n        kept.append(n)',
    note: 'Removing shifts later items left, so the loop skips the item after each removal. Build a new list of the items you want to keep.',
  },
  {
    mistake: 'sort_tiebreak',
    bad: 'ranked = sorted(scores, key=lambda s: s[1], reverse=True)',
    good: 'ranked = sorted(scores, key=lambda s: (-s[1], s[0]))',
    note: 'If the task says "then by name", the name belongs in the key. A negative number sorts high to low while the name still sorts A to Z.',
  },
  {
    mistake: 'mutated_input',
    bad: 'def top_three(marks):\n    marks.sort(reverse=True)\n    return marks[:3]',
    good: 'def top_three(marks):\n    ordered = sorted(marks, reverse=True)\n    return ordered[:3]',
    note: 'A list passed into a function is the caller\'s own list. Sorting or removing inside the function changes their data, which hidden tests check.',
  },
  {
    mistake: 'return_type_wrong',
    bad: 'def lowest_highest(temps):\n    return [min(temps), max(temps)]',
    good: 'def lowest_highest(temps):\n    return (min(temps), max(temps))',
    note: 'When the spec says "return a tuple", a list with the same values is marked wrong. `(a, b)` is a tuple; `[a, b]` is a list.',
  },
];
